### ISSUE TITLE
Le fichier de mire de test "/tmp/DisplayCAL..." n'a pas pu être créé...

### ISSUE THREAD

**Issue by manu-p** [eoyilmaz/displaycal-py3#106]
Hi, sorry for the subject in french, but I don't know the english translation.

Installed displaycal-py3 on an Ubuntu 20.04 system under /opt.

Works fine until the end when I get a popup telling me:

> Le fichier de mire de test "/tmp/DisplayCAL-3qjsmhoz/2022-05-11 943 110cdm² D6500 2.2 S LalbLUT.ti1" n'a pas pu être créé. Peut-être y a-t-il des restrictions d'accès, ou bien le fichier source n'existe pas.
> 
> initial_value must be str on Non, not bytes

Found the error message here for MacOS but does not sound to be the same issue.

I can find references to the file (apart its ti1 extension) here: /home/manu/.local/share/dispcalGUI/incomplete/2022-05-11 943 110cdm² D6500 2.2 S LabLUT but it stores a .cal, .log and a .ccmx files.

No access restrictions to /tmp as far as I know.

**Comment by eoyilmaz** [comment]
Hey thank you for reporting, so did your problem get solved after removing the files? I didn't understand sorry.

**Comment by manu-p** [comment]
I did solve the issue, apart an error (warning?) message at the end saying the profile had to be installed using the system "color" parameters settings but when I open these settings the profile displayCal just created is already installed. 

So far, the issue is solved (as far as I'm concerned).

**Comment by eoyilmaz** [comment]
Okay then thank you for reporting. I'm closing this issue :+1:
