### ISSUE TITLE
Error: the testchart file could not be created.

### ISSUE THREAD

**Issue by andresolnik** [eoyilmaz/displaycal-py3#109]
Calibration apparently runs fine, but at the very end I get the following error:

```
2022-05-13 01:09:21,335 The instrument can be removed from the screen.
2022-05-13 01:09:21,359 Written calibration file 'U2715H 2022-05-13 2.2.cal'
2022-05-13 01:09:21,360 DisplayCAL: Reached EOF (OK)
2022-05-13 01:09:21,462 dispcal exitcode: 0
2022-05-13 01:09:21,506 Error('The testchart file “/tmp/DisplayCAL-y0ulxo75/U2715H 2022-05-13 2.2.ti1” could not be created. Maybe there are access restrictions, or the source file does not exist.\n\ninitial_value must be str or None, not bytes')
```

I'm running displaycal-py3 3.9.3 on Debian testing.

**Comment by eoyilmaz** [comment]
There seems to be a couple of problems:

- Firstly, I believe, you tried to install the profile system wide, and probably your user is not in sudoers. But this is not certain to me and I need feedback on that.
- Also can you check if there is a ``/tmp`` folder. Some distros have their temp folder in ``/var/tmp``, some have both etc.
- And apparently we have another ``str/bytes`` issue. But this could happened while trying to concatenate the original error message with some variables and this is not crucially important. But of course we need to fix it.

Also running displaycal with ``-d`` argument will print out more messages which may help figuring out the problem.

**Comment by andresolnik** [comment]
Thanks for your reply. I wasn't trying to install the profile system wide. The installation path is `~/.local/share/dispcalGUI/storage` and, yes, there is a `/tmp` directory.

Anyway, just before reading your message I gave a shot upgrading outdated PIP packages (certifi, numpy, Pillow and wxPython) and it worked (not sure why though). But now, when I click the Calibrate & profile button I get this error message: `Warning: No language files found.` and the measure frame window looks a bit strange.

![Captura de tela_2022-05-16_23-52-24](https://user-images.githubusercontent.com/54610938/168719307-4d286d90-a7c9-44c5-aebf-6b872e8349ae.png)
`

**Comment by eoyilmaz** [comment]
Are you installing through the tarball or PyPI or are you directly running it through the source?

**Comment by andresolnik** [comment]
through PyPI

**Comment by eoyilmaz** [comment]
Ah okay then can you upgrade to 3.9.4 and try again.

**Comment by andresolnik** [comment]
Everything is working as expected now, thanks.

**Comment by eoyilmaz** [comment]
you're welcome :+1:
