### ISSUE TITLE
Build for linux 32bits failing

### ISSUE THREAD

**Issue by papoteur-mga** [eoyilmaz/displaycal-py3#111]
Trying to build for 32bits arch on Mageia.
I get this error:
```
copying DisplayCAL/lib/agw/pygauge.py -> build/lib.linux-i686-3.10/DisplayCAL/lib/agw
copying DisplayCAL/lib/agw/fmresources.py -> build/lib.linux-i686-3.10/DisplayCAL/lib/agw
error: package directory 'DisplayCAL/lib32' does not exist
```

Indeed, this directory doesn't exist in realease tarball.
However, even it was included, setup.py would try to found python38 python39 and python310 sub-directories which don't exist neither.
And I don't think it would be useful to have precompiled libraries. For distro POV, the libraries have to be build at packaging step.

**Comment by eoyilmaz** [comment]
Yeah, sorry I removed 32 bit support, thinking that even Raspberry Pi's have a 64-bit distro.

**Comment by papoteur-mga** [comment]
We still have support for x86 and for armv7.
I had to remove the copy step of *.so in DisplayCAL/setup.py

**Comment by eoyilmaz** [comment]
I can bring back the 32-bit support if it is so crucial, what do you think.

**Comment by eoyilmaz** [comment]
Hey @papoteur-mga can you check if b99f122 is solving your issue, thank you
