### ISSUE TITLE
ICC Profile info broken

### ISSUE THREAD

**Issue by sushi2503** [eoyilmaz/displaycal-py3#114]
Hi,

Since version 3.9.3-1 the profile info is not showing any profile nor info because of "outdated" wxPython version 4.0.7.post2 and should be at least 4.1.1. By clicking the button maximize window it freezes with the wxPython outdated warning.

Archlinux up to date.

Thanks.

**Comment by eoyilmaz** [comment]
Okay, I made ``wxPython>=4.1.1`` the default requirement for ``DisplayCAL`` with e7016276908ec0f02604e436df31cfa5276b86b7

**Comment by eoyilmaz** [comment]
Sorry, reopenned this issue, I now see the problem:

![image](https://user-images.githubusercontent.com/1786804/168589370-bdc5da9d-8d75-413c-b46d-1aa99fdde3f8.png)

**Comment by sushi2503** [comment]
Thanks,
Yes this is the window with the same errors.

**Comment by eoyilmaz** [comment]
Can you check the latest commit from the ``develop`` branch, I think I've fixed it, though, we have some weird problems with this UI when it gets maximized.

**Comment by sushi2503** [comment]
Ok, as soon as I will know where to find the develop branch.

Thanks.

**Comment by eoyilmaz** [comment]
I mark this as solved, but please open it again if you still have issues.
