### ISSUE TITLE
The last command line of the "How to install" in the README.md file is wrong

### ISSUE THREAD

**Issue by ignace72** [eoyilmaz/displaycal-py3#116]
Good evening.   
The last command line of the "How to install" in the README.md file is wrong.   
If you type :   
`pip install dist/DisplayCAL-3.9.0-*.whl`   
It will not work because the current version of DisplayCAL is not 3.9.0.   
You should therefore use the command :   
`pip install dist/DisplayCAL-3.9.4-*.whl`   
It would be even easier to delete the content of the displaycal-py3 directory to start from a clean base for each new version and use the command :   
`pip install dist/DisplayCAL-3.9.*.whl`

**Comment by eoyilmaz** [comment]
Fixed in f5c20151
