### ISSUE TITLE
Wrong requirements.txt file for develop branch

### ISSUE THREAD

**Issue by Nilvus** [eoyilmaz/displaycal-py3#126]
Hi @eoyilmaz,
First, many thanks to you for providing DisplayCal with Python3. Was good to remove my only flatpak package to replace it by your work.

I have had issue when following README instructions on your repository.

You suggest to use develop branch and so what I have done (and I'm used to use develop branch on darktable).

Following instructions, when launching `python -m build`, I have an error saying that there's no module named build.
It takes me times to understand that I have too install it with pip (I'm not familiar with PyPy).

I then see that there is 2 requirements files:

- requirements.txt (with few modules listed and no build one)
- requirements-dev.txt (with more modules and build one listed)

So, requirements-dev.txt should replace requirements.txt, at least on develop branch. Or amend README.md file to precise to use requirements-dev.txt for develop branch?

If needed, I can fork your repository to provide one of those fix you prefer.

**Comment by eoyilmaz** [comment]
Ah yeah sorry this is my fault I recently transferred ``build`` package from ``requirements.txt`` to ``requirements-dev.txt``, will revert it back :+1:
