### ISSUE TITLE
`wxPython` out of date error; any way to add a min-version requirement to the `pip` package for auto-upgrade?

### ISSUE THREAD

**Issue by kwand** [eoyilmaz/displaycal-py3#128]
As titled. I got the following error when trying to do a profile verification (not that I believe this matters; probably would have crashed elsewhere if not here):

![image](https://user-images.githubusercontent.com/16279847/171805501-ca194bea-3cd8-4dde-9263-18a02189f6e8.png)

Any way this could be fixed by adding a minimum version requirement to the `pip` package, or is this not related to `displaycal-py3`?

EDIT: Actually, it seems like this is just an instance of #61 with a warning at the bottom. Upgrading `wxPython` did not fix the error.

**Comment by eoyilmaz** [comment]
The ``wxPython`` warning is just a warning and what you get is another error. But, the error you get is different than #61, as I see.

**Comment by eoyilmaz** [comment]
I've updated the ``develop`` branch with a possible fix. Can you try and report back, thank you!

**Comment by eoyilmaz** [comment]
closing this for being inactive and old...
