### ISSUE TITLE
Error while wiriting calibration results

### ISSUE THREAD

**Issue by Lorentz83** [eoyilmaz/displaycal-py3#129]
I just compiled the develop branch (a872f5e7254536bc30ce73cb59ec8ed509807df1), I can start DisplayCAL and it correctly recognizes my spider 3, I start the calibration as expected, I can see all the patches changing on the monitor. But when it finishes I get the following error

```
The testchart file "/tmp/DisplayCAL-8spae3g8/rincewind VC3211-2k 2022-06-05 13-08 2.2 F-S ZYZLUT+MTX.ti1" 
could not be created. Maybe there are access restrictions, or the source file does not exist.

initial_value must be str or None, not bytes
```

I checked and the directory /tmp/DisplayCAL-8spae3g8 doesn't exist, but it can be created (no weird permission on /tmp and plenty of disk space).

In the terminal I can see
```
Written calibration file 'rincewind VX3211-2K 2022-06-05 13-08 2.2 F-S XYZLUT+MTX.cal'

DisplayCAL: Reached EOF (OK)
dispcal exitcode: 0
Moving files of incomplete run to /home/lorenzo/.local/share/DisplayCAL/incomplete/rincewind VX3211-2K 2022-06-05 13-08 2.2 F-S XYZLUT+MTX
```

In this directory I can find the cal file but not the icc.

In the main DisplayCAL UI I can see the calibration file in the settings dropdown, but the install button is disabled.

Please let me know if there is further information I can attach to make debugging easier.

**Comment by eoyilmaz** [comment]
I think it is something related to the ``initial_value must be str or None, not bytes`` message. Let me check it quickly.

**Comment by eoyilmaz** [comment]
Do you have the ".ti3" file in that directory? Can you upload it here if you have, thank you.

**Comment by Lorentz83** [comment]
Yes, there is (I renamed it as txt otherwise github doesn't allow me to upload it)
[0_16.ti3.txt](https://github.com/eoyilmaz/displaycaYel-py3/files/8840498/0_16.ti3.txt)

**Comment by eoyilmaz** [comment]
Thank you

**Comment by eoyilmaz** [comment]
The file content is ``Not Found``, this is not done by you, right?

**Comment by Lorentz83** [comment]
There is definitely stuff inside. Let me try uploading it again.

[0_16.ti3.txt](https://github.com/eoyilmaz/displaycal-py3/files/8840575/0_16.ti3.txt)

**Comment by eoyilmaz** [comment]
Okay, this time I see data, thank you.

**Comment by eoyilmaz** [comment]
This is possibly fixed. Can you try the latest ``develop`` branch commit and report back, thank you :+1:

**Comment by Lorentz83** [comment]
tried on commit `9f492714fbc0e2205d83f09c2f7db82a4b4c75d7` and now I get a different error:

```
The testchart file [very long pathname in local share].icc is invalid
```

I'm not very familiar with the python build pipeline, I wonder if I updated it correctly. I run:

```
python3 -m venv ./displaycal_venv 
source ./displaycal_venv/bin/activate             
cd ./displaycal-py3/      
pip install -r requirements.txt 
python -m build  
pip install --force-reinstall dist/DisplayCAL-3.9.*.whl   
```

I used the `--force-reinstall` option otherwise pip complained that it was already installed.

**Comment by eoyilmaz** [comment]
Can you also upload this file:

```shell
/home/lorenzo/.local/share/DisplayCAL/storage/750 #1 2017-02-15 22-30 2.2 S XYZLUT+MTX/750 #1 2017-02-15 22-30 2.2 S XYZLUT+MTX.icc
```

**Comment by Lorentz83** [comment]
Here all of them

[debug.zip](https://github.com/eoyilmaz/displaycal-py3/files/8884228/debug.zip)

**Comment by eoyilmaz** [comment]
Thank you

**Comment by eoyilmaz** [comment]
The ICC file seems pretty valid. This is strange. Let me further investiage.

**Comment by eoyilmaz** [comment]
@Lorentz83 can you pull the latest ``develop`` branch and try again. I did fix a couple of possible errors. But, I'm not sure if I found the error that causes your problem. But, let's try :crossed_fingers:

**Comment by eoyilmaz** [comment]
@Lorentz83 I've released DisplayCAL 3.9.6 yesterday, if you like you can directly install through pip too.

**Comment by Lorentz83** [comment]
I just finished trying with the version 3.9.7 (commit 05dbbda00c05b49f5e4314892b154fd22c180394), and in the first run I got the same error. But later I tried again after removing `$HOME/.local/share/DisplayCAL/` and it worked. I guess if it was picking up some broken configuration from the old runs.

Thank you for the effort to keep this great project alive!

**Comment by eoyilmaz** [comment]
Thank you, it is good to know that it is fixed now :+1:
