### ISSUE TITLE
Wayland: Argyll Measure Frame is not displaying in the correct position.

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#130]
Under Wayland, the Argyll measure frame is not displaying in the correct position where the ``wxMeasureFrame`` has been set.

**Comment by Betameche** [comment]
Hi,
I'm just here to confirm that last bug is fixed for me, and that the measuring window is not correctly positionned. It's consistent with the P parameter passed to dispcal though.

**Comment by eoyilmaz** [comment]
Exactly, I tried it, Argyll can place the window in the correct position already. It is DisplayCAL who can not read the correct position of the ``wxMeasureFrame`` I think.

**Comment by eoyilmaz** [comment]
This seems to be a dead end: https://stackoverflow.com/a/59698493/3259351

So I probably need rollback some changes I did for the #124 and let the wxMeasureFrame be shown as a Frame (as Florian did) or always set it to the screen center.

**Comment by eoyilmaz** [comment]
Interestingly, as I learned by reading the [Blue Recorder’s](https://github.com/xlmnxp/blue-recorder/blob/master/src/area_capture.rs) code the `xwininfo` command can read the size and position of a window under Wayland. But, I was not able to read the MeasureFrame size and position by using it. I believe it is because the Measure Frame window is a wxFrame. I’ll investigate that further.
