### ISSUE TITLE
RealDisplaySizeMM.so

### ISSUE THREAD

**Issue by marjue12255** [eoyilmaz/displaycal-py3#14]
Hello

I've tried the code under MacOS with Apple Silicon. I get different errors if I use Python 3.9.10 in the Intel version or in the ARM version.

I think best option is to use Python in it's ARM version. But this needs a lib with this arch.

With Intel Python:
-------------------

[marcus:displaycal-py3]$ ./DisplayCAL-profile-info.pyw
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7f8cf0174fa0>
DisplayCAL-profile-info.pyw 0.0.0.0 0000-00-00T00:00:00.0Z
Mac OS X 10.16 x86_64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 17:02:14)
[Clang 6.0 (clang-600.0.57)]
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: UTF-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
Lockfile /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-VRML-to-X3D-converter.lock
Existing client using port 56806
Lockfile /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.lock
listening
_**/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxMeasureFrame.py:25: Warning: dlopen(/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/lib64/RealDisplaySizeMM.so, 0x0002): symbol not found in flat namespace '_PyString_FromString'**_
  warnings.warn(str(exception), Warning)
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/main.py", │
│ line 463, in main                                                            │
│     _main(module, name, applockfilename)                                     │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/main.py", │
│ line 450, in _main                                                           │
│     main()                                                                   │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxProfileInfo.py", │
│ line 1841, in main                                                           │
│     app.TopWindow = ProfileInfoFrame(None, -1)                               │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxProfileInfo.py", │
│ line 977, in __init__                                                        │
│     self.view_3d_btn = BitmapButton(p1, -1, geticon(16, "3D"),               │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxfixes.py", │
│ line 1159, in __init__                                                       │
│     set_bitmap_labels(self)                                                  │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxfixes.py", │
│ line 976, in set_bitmap_labels                                               │
│     bmp = get_bitmap_hover(bitmap, btn)                                      │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxfixes.py", │
│ line 878, in get_bitmap_hover                                                │
│     if minv == 256 and alphabuffer[j] > "\x20":                              │
│ TypeError: '>' not supported between instances of 'int' and 'str'            │
└──────────────────────────────────────────────────────────────────────────────┘

With ARM Python
------------------

[marcus:displaycal-py3]$ ./DisplayCAL-profile-info.pyw
Acquired lock file: <DisplayCAL.main.AppLock object at 0x102dc8d30>
DisplayCAL-profile-info.pyw 0.0.0.0 0000-00-00T00:00:00.0Z
Mac OS X 12.2.1 arm64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45)
[Clang 13.0.0 (clang-1300.0.29.30)]
CA file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: UTF-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
Lockfile /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-VRML-to-X3D-converter.lock
Existing client using port 56806
Lockfile /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.lock
listening
/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxMeasureFrame.py:25: Warning: dlopen(/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/lib64/RealDisplaySizeMM.so, 0x0002): tried: '/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3[marcus:displaycal-py3]$ ./DisplayCAL-profile-info.pyw
Acquired lock file: <DisplayCAL.main.AppLock object at 0x102dc8d30>
DisplayCAL-profile-info.pyw 0.0.0.0 0000-00-00T00:00:00.0Z
Mac OS X 12.2.1 arm64
Python 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:45)
[Clang 13.0.0 (clang-1300.0.29.30)]
CA file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.1.1 osx-cocoa (phoenix) wxWidgets 3.1.5
Encoding: UTF-8
File system encoding: utf-8
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL.ini
Loading /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.ini
Lockfile /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-VRML-to-X3D-converter.lock
Existing client using port 56806
Lockfile /Users/marcus/Library/Preferences/DisplayCAL/DisplayCAL-profile-info.lock
listening
_**/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxMeasureFrame.py:25: Warning: dlopen(/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/lib64/RealDisplaySizeMM.so, 0x0002): tried: '/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/lib64/RealDisplaySizeMM.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/RealDisplaySizeMM.so' (no such file)**_
  warnings.warn(str(exception), Warning)
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/main.py", │
│ line 463, in main                                                            │
│     _main(module, name, applockfilename)                                     │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/main.py", │
│ line 450, in _main                                                           │
│     main()                                                                   │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxProfileInfo.py", │
│ line 1841, in main                                                           │
│     app.TopWindow = ProfileInfoFrame(None, -1)                               │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxProfileInfo.py", │
│ line 977, in __init__                                                        │
│     self.view_3d_btn = BitmapButton(p1, -1, geticon(16, "3D"),               │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxfixes.py", │
│ line 1159, in __init__                                                       │
│     set_bitmap_labels(self)                                                  │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxfixes.py", │
│ line 976, in set_bitmap_labels                                               │
│     bmp = get_bitmap_hover(bitmap, btn)                                      │
│   File                                                                       │
│ "/Users/marcus/Entwicklung/github/displaycal-py/displaycal-py3/DisplayCAL/wxfixes.py", │
│ line 878, in get_bitmap_hover                                                │
│     if minv == 256 and alphabuffer[j] > "\x20":                              │
│ TypeError: '>' not supported between instances of 'int' and 'str'            │
└──────────────────────────────────────────────────────────────────────────────┘
Exiting DisplayCAL-profile-info

**Comment by eoyilmaz** [comment]
Thank you for the bug report.
Can you try it with the latest version of the code, I suspect it is already fixed.

**Comment by marjue12255** [comment]
Hello Erkan
Yes I can confirm that it's fixed. I'm still using the Intel version of Python at the moment. The library seams to be for i386 and x86_64 arch until now. Is this right? 

Bye
Marcus

**Comment by eoyilmaz** [comment]
In ideal conditions it should also work with ARM. Can you please keep testing it with the Apple Silicon and report bugs you encountered. Thank you :+1:

**Comment by marjue12255** [comment]
Hello
I will install the ARM version again in the next days besides the Intel version to test both.
Let's see if we have an ideal world at least on our computers ;-). 

Bye
Marcus
