### ISSUE TITLE
Files missing from tarball

### ISSUE THREAD

**Issue by dfandrich** [eoyilmaz/displaycal-py3#147]
DisplayCAL-3.9.6.tar.gz is missing files that exist in git such as misc/45-Argyll.rules whose absence causes installs to fail with:

`error: can't copy '/home/user/rpm/BUILD/DisplayCAL-3.9.6/DisplayCAL/../misc/45-Argyll.rules': doesn't exist or not a regular file`

**Comment by eoyilmaz** [comment]
We have removed that file after the long discussions in #117

What command are you using to install the tarball?

**Comment by dfandrich** [comment]
The install command is:

`/usr/bin/python3 setup.py install -O1 --skip-build --root /home/user/rpm/BUILDROOT/displaycal-3.9.6-1.lcl9.x86_64 --no-compile --prefix=/usr --skip-postinstall`

If 45-Argyll.rules file was deliberately removed, its ghost is still present:

```
$ grep -rl 45-Argyll.rules DisplayCAL-3.9.6/ | wc -l
7
```

**Comment by dfandrich** [comment]
DisplayCAL-3.9.11 now has a different missing file when that install command is used:

  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/DisplayCAL-3.9.11/misc/debian.rules'

Creating a dummy `misc/debian.rules` allows the install to run to completion. There are still the same number of references to the file `45-Argyll.rules`, and the file is still missing, but at least the install process succeeds with this workaround.

**Comment by eoyilmaz** [comment]
I believe Debian now has a proper package for DisplayCAL and it should be working properly.
