### ISSUE TITLE
Please delete generated RealDisplaySizeMM.so files and python2 directories

### ISSUE THREAD

**Issue by marillat** [eoyilmaz/displaycal-py3#153]
Binary generated files must not been put in the tarball.
Files are 
`DisplayCAL/lib64/RealDisplaySizeMM.so`
`DisplayCAL/lib64/python26/RealDisplaySizeMM.so`
`DisplayCAL/lib64/python27/RealDisplaySizeMM.so`
`DisplayCAL/lib32/RealDisplaySizeMM.so`
`DisplayCAL/lib32/python26/RealDisplaySizeMM.so`
`DisplayCAL/lib32/python27/RealDisplaySizeMM.so`

Directories are
https://github.com/eoyilmaz/displaycal-py3/tree/main/DisplayCAL/lib32/python26
https://github.com/eoyilmaz/displaycal-py3/tree/main/DisplayCAL/lib32/python27
https://github.com/eoyilmaz/displaycal-py3/tree/main/DisplayCAL/lib64/python26
https://github.com/eoyilmaz/displaycal-py3/tree/main/DisplayCAL/lib64/python27

**Comment by eoyilmaz** [comment]
Hmmm that’s interesting there shouldn’t be any. I’ll check it whenever I got myself in front of my workstation.
