### ISSUE TITLE
an issue under Ubuntu 20.04

### ISSUE THREAD

**Issue by cherob67** [eoyilmaz/displaycal-py3#154]
I have installed the last version using pip install successfully. When  i try to run displaycal, i have an issue with a popup windows : 

__________________________________________________________________________________
'float' object cannot be interpreted as an integer

Traceback (most recent call last):

File "/home/xxxx/.local/lib/python3.10/site-packages/wx/core.py", 
line 3407, in <lambda>
  lambda event: event.callable(*event.args, **event.kw) )

File "/home/xxxx/.local/lib/python3.10/site-packages/DisplayCAL/display_cal.py",
line 712, in donation_message
 dlg = ConfirmDialog(

File "/home/xxxx/.local/lib/python3.10/site-packages/DisplayCAL/wxwindows.py",
line 3115, in __init__
BaseInteractiveDialog.__init__(

File
"/home/xxxx/.local/lib/python3.10/site-packages/DisplayCAL/wxwindows.py",
line 2529, in __init__
wx.Dialog.__init__(self, parent, id, title, pos, size, style, name)
TypeError: 'float' object cannot be interpreted as an integer
__________________________________________________________________________________

Have you an idea ?

**Comment by p5k369** [comment]
Hey @cherob67, there are still several places in the code where the size value has to be an integer but a float is provided. They will be sorted out sooner or later. Take a look at #158. If this is the only place failing, it might work for you.

**Comment by p5k369** [comment]
Fixed in #158

**Comment by p5k369** [comment]
#189 should now solve the problem, my first change made it in fact worse, cant say what I was thinking at that moment, sry.

**Comment by p5k369** [comment]
Finally fixed in #189
