### ISSUE TITLE
Get rid of ``RealDisplaySizeMM`` C-Extension

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#16]
The ``RealDisplaySizeMM`` C-Extension seems to be doing something that can be done using pure Python. Though, this needs further investigation.

Also, this ticket is related to #6, if this ticket is solved, there is no need to solve #6 .

**Comment by eoyilmaz** [comment]
Under Linux systems, ``xrandr --verbose`` gives all the info we need, including EDID which needs to be decoded:

```python
import codecs
edid = codecs.decode(xrandr_edid_data, "hex")
```

I have no experience with Wayland though, so I don't know if ``xrandr`` behaves the same.

**Comment by p5k369** [comment]
I think the main reason for using the C-Extension at the time was making it work under macos, maybe that is obsolete now.
Heres the story how `RealDisplaySizeMM` found its way into DisplayCAL:
https://www.python-forum.de/viewtopic.php?f=19&t=15859

**Comment by eoyilmaz** [comment]
Thanks for the link. It was delighting to read. Though, it is really not enough motivation to use a C-Extension as far as I'm concerned. We should definitely remove it.

**Comment by eoyilmaz** [comment]
Let's do this... 😎

**Comment by eoyilmaz** [comment]
Good news, currently on my Macbook Pro running MacOS I can run DisplayCAL and do a full calibration and profiling without needing to build and use the extension. All the information is extracted from the `dispwin` command, which currently is the display name, width, height and the position. There are other data that needs to be gathered, but I think DisplayCAL will fallback to default values if the required data doesn't exist.

But, under Linux, the `DisplayCAL.edid.get_edid()` was using `DisplayCAL.RealDisplaySizeMM._enumerate()` to extract the EDID information. We need to update the code to extract the EDID from `xrandr --verbose` command. So I need some sample outputs of the `xrandr --verbose` command to build my tests around.

Any help is appreciated.

@p5k369 I think you were using a Linux machine, can you help me with this, please?

**Comment by p5k369** [comment]
Hey @eoyilmaz,
great work.  I think mac OS that was the main reason why the c-extension was used in the first place.
Find attached the output for one display connected.
[xrandr_output.txt](https://github.com/user-attachments/files/17458218/xrandr_output.txt)

Do you also need an example for multiple displays connected?

**Comment by eoyilmaz** [comment]
Great, many thanks @p5k369

**Comment by eoyilmaz** [comment]
@p5k369 can you also send me the output of `dispwin -v -d0` for those two conditions too please, many thanks.

**Comment by eoyilmaz** [comment]
Ah, I was able to mock the output of `dispwin` through the information available by the `xrandr` output 👍

**Comment by eoyilmaz** [comment]
This should now be working under Linux. @p5k369 would you like to test it.

Ofcourse there are missing features, like the `size_mm` attribute of a display will always return `(0, 0)` which we can connect directly to the resolution through DPI. On the otherhand, we can completely skip it and don't care.

Also with the new Apple Silicons the `ioreg` is not returning the EDID data anymore. But, this is unrelated to the C-Extension as it was not used to retreive the EDID data under macOS at all (although it might be able to retrieve it).

**Comment by p5k369** [comment]
@eoyilmaz Works as intended.

**Comment by eoyilmaz** [comment]
Tested under MacOS Sonoma, Windows 10 and Fedora 40, and virtual Ubuntu 24.10 and everything seem to be working fine.
