### ISSUE TITLE
`dbus-python` build error on Framework build of python

### ISSUE THREAD

**Issue by TylerLoewen** [eoyilmaz/displaycal-py3#162]
I ran into issues when following the install instructions on MacOS using pyenv and python 3.10.6. Here is my process.

## Broken
1. Install python 3.10.6 using `pyenv install 3.10.6`
2. Create the virtualenv
3. switch to develop branch
4. Install displayCal
```
pip install -r requirements.txt
python -m build
pip install dist/DisplayCAL-3.9.*.whl
```
6. run `displaycal` which gets
```
Acquired lock file: <DisplayCAL.main.AppLock object at 0x100f13df0>
displaycal 3.9.8 2022-08-21T17:08:34Z
Mac OS X 12.5.1 arm64
Python 3.10.6 (main, Aug 21 2022, 12:01:33) [Clang 13.1.6 (clang-1316.0.21.2.5)]
CA file /Users/tylerloewen/.pyenv/versions/3.10.6/lib/python3.10/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.2.0 osx-cocoa (phoenix) wxWidgets 3.2.0
Encoding: utf-8
File system encoding: utf-8
Loading /Users/tylerloewen/Library/Preferences/DisplayCAL/DisplayCAL.ini
listening
writing to lock file: port: 15411
Starting up...
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
Ran application exit handlers
```

Repeating these steps again but with the  framework version of python gets me a `dbus-python` error:

```
configure: error: in `/private/var/folders/k1/0vgdvk6s54q_m901k6c377bh0000gn/T/pip-install-coxo5567/dbus-python_27f8673d4d2749a0bc2d4ab58790652d/build/temp.macosx-12.5-arm64-cpython-310':
      configure: error:
        Could not link test program to Python. Maybe the main Python library has been
        installed in some non-standard library path. If so, pass it to configure,
        via the LIBS environment variable.
        Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
        ============================================================================
         ERROR!
         You probably have to install the development version of the Python package
         for your distribution.  The exact name of this package varies among them.
        ============================================================================
```

## Working

1. install framework version of python 3.10.6 using `PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.10.6`
3. Create the virtualenv
4. switch to develop branch
5. Change the `dbus-python`  dependency in `requirements.txt` and `setup.cfg` to `dbus-next`
6. Build as per README instructions
7. `displaycal` command now properly launches DisplayCal

Not sure if it makes sense to switch from `dbus-python` to `dbus-next`, or if this will break things down the line. There are possibly other solutions to my original problem as well that doesn't involve changing a dependency but I couldn't figure it out after trying a few things.

**Comment by eoyilmaz** [comment]
Hmm... I looked in to the code paths that import ``dbus`` and I think under MacOS (and also under Windows) ``dbus`` is not used at all in DisplayCAL and we should not try to install it.

**Comment by eoyilmaz** [comment]
Okay it is now possible to install and run on MacOS without any issues (though, I didn't test anything else than running the software).
