### ISSUE TITLE
Replace the ``wexpect.py`` with the latest release of ``Wexpect``

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#17]
Replace the ``wexpect.py`` with the latest release of ``Pexpect``. I'm not very familiar with this module, and there is no comment in the code on why we have a ``wexpect.py`` instead of using the PyPI version of ``Pexpect``. Reading the module documentation seems that this module is a modified version of a very old version of ``Pexpect``. Using the modern version of ``Pexpect`` would benefit the code and possibly make the modifications obsolete.

**Comment by p5k369** [comment]
I think that's because of offering windows compatibility. https://pexpect.readthedocs.io/en/stable/overview.html#windows

**Comment by eoyilmaz** [comment]
Our wexpect is working properly right now, and I feel we don't need to replace it.
