### ISSUE TITLE
Testchart editor cannot parse some files

### ISSUE THREAD

**Issue by ledoge** [eoyilmaz/displaycal-py3#170]
Under the Profiling tab, when I select "Default testchart" and then click the icon to open the testchart editor, it gives me the following error:

```
The testchart file “/usr/share/DisplayCAL/ti1/d3-e4-s3-g52-m3-b0-f0.ti1”
could not be read.

'int' object is not iterable
```

The testchart editor still opens and seems to work, but the patches from the selected testchart are not present.

**Comment by p5k369** [comment]
Hey @ledoge, check out #176, that should fix the problem.

**Comment by eoyilmaz** [comment]
thanks everyone for both reporting and solving this issue... closing this now.
