### ISSUE TITLE
[bug] DisplayCal useless on macOS 12.5.1

### ISSUE THREAD

**Issue by KingOfBaboon** [eoyilmaz/displaycal-py3#172]
Hi I'm recently getting into the color management world with xtie i1 display studio and 2018 macbook pro.

First, want to thank you to pick up this great project and make it even better. (btw is it possible that we make this repo more obvious on `[https://displaycal.net/`](https://displaycal.net/) or the documentation?)

Here's what happened for me:
I've been trying to calibrate the macbook pro display with DisplayCal and got inconsistent results(the most obvious discrepancy is the DCI-P3 gamut coverage, which is supposed to be close to 100% on this monitor).
tried a lot of different settings to reproduce this problem and turns out it's something outside DisplayCal - the macOS monitor  color profile setting from system settings:

- whenever I chose the `Color LCD`(the default icc on macOS, covering 100% P3 gamut) before calibration, I got a result from DisplayCal which covers only 80% P3 gamut - not ideal.
- Whenever I chose the `sRGB` icc before calibration, I got a result from DisplayCal which covers 100% P3 gamut - sounds better but I'm not sure it's the result I want or need.

I was surprised and did more research, this [youtube video](https://www.youtube.com/watch?v=xywb1_vpQhI&t=257s) claims all calibration software would automatically switch the icc on target display to a standard linear baseline icc setting during the calibration.  I think that make sense - calibration software need a static starting point to measure those patches and compare/calculate/adjust so that a deterministic result can be achieved only depending on the monitor itself, but not which icc was been used before calibration.

I confirmed the xrite software ccStudio does that - I can see the icc on my display switched to `DisplayProfile_Linear.icc` the second it starts calibration. But DisplayCal is not doing that.

I moved from 3.8.9.3 to this build and still the same.

We had some [discussion](https://hub.displaycal.net/forums/topic/super-obvious-question-about-previous-iccs-affecting-calibration/) on DisplayCal forum without valid conclusion.

Also, logs like this 
> About to overwrite existing /home/coleg/.local/share/icc/DisplayCAL Linear Calibration sRGB Profile.icc

from other issue #139  makes me believe such a `a standard linear baseline icc setting` exists in DisplayCal and should be used. But not in my case.

 
So here's my question:

- Should DisplayCal auto switching ICC on target display during calibration?
  - if yes, there's a bug somewhere, let's find and fix.
  - if no, this `standard linear baseline icc` should be provided and documented clearly to use before calibration so we can get consistent results.

Thanks again!

**Comment by KingOfBaboon** [comment]
I think this [post](https://hub.displaycal.net/forums/topic/profile-to-dark-levels/#post-21554) from Florian answered my question: 
`Calibration & profiling always overrides any assigned profiles.`

Somehow DisplayCal is not able to do that on macOS now(I can test it later on windows), maybe due to macOS version update and permission changes.

A workaround would be to find out the `baseline` ICC profile DisplayCal is supposed to use, and set it manually before calibration. 

e.g xrite use `XRite_LinearProfile.icc.zip`, we need the equivalent for DisplayCal, but I guess every software is using its own baseline in the implementation so I can't just use Xrite for DisplayCal.

I think it's a major bug, basically making DisplayCal useless on macOS.

**Comment by KingOfBaboon** [comment]
ok, it's a macOS thing, Windows11 works fine, the monitor is set to a certain baseline color when the calibration starts, I can see an obvious color change from my manual-set icm and DisplayCal's own baseline profile - need to find it out what it is - looks very similar to `Reset video card gamma table` from the window DisplayCal profile loader.

**Comment by eoyilmaz** [comment]
Hey @KingOfBaboon yeah this is basically what DisplayCAL does on other OSes. MacOS updates generally breaks things, I guess it is related to that. I'll look in to this hopefully soon :+1:

**Comment by eoyilmaz** [comment]
I now have access to a MacBook Pro M1 Pro and hopefully will look in to this one shortly.

**Comment by eoyilmaz** [comment]
Closing this as the latest versions of DisplayCAL runs smootly on macOS.
