### ISSUE TITLE
Weird dropdown under Verification tab should not be visible

### ISSUE THREAD

**Issue by ledoge** [eoyilmaz/displaycal-py3#178]
Under the Verification tab, I can see an unlabeled "Output profile" dropdown below the "Device link profile" one that should not be visible (as far as I can tell). It's defined [here](https://github.com/eoyilmaz/displaycal-py3/blob/4eff4afbe11b8c3ba7bfb43992d21f57e9dd0e0f/DisplayCAL/xrc/report.xrc#L314) and set to hidden, and I've never seen it on the latest Windows release. Looking at the code, I don't even see a way for it to get set to visible, so I'm kinda confused.

It's the bottom one in this screenshot:
![2022-09-11_23-42](https://user-images.githubusercontent.com/8040316/189550191-4eb03bea-1f95-4a8f-a915-d8ed4e37fa54.png)

**Comment by eoyilmaz** [comment]
Can you share the whole window, I don't have that option, and I need more data to reproduce it.

**Comment by ledoge** [comment]
It's always there for me no matter what settings I use. Here's what I just did:

1. Check out the latest development branch
2. Delete the DisplayCAL folder under ~/.config
3. Start DisplayCAL with a colorimeter (i1Display) connected
4. Switch to the verification tab
5. Select a different preset (sRGB) that populates the dropdown so it's easier to see

Screenshot:

![2022-09-17_15-08](https://user-images.githubusercontent.com/8040316/190858737-b42570b2-ee65-4251-b648-e54b566aa04d.png)

The dropdown is also there in release 3.9.6 as installed via the package manager of my OS (Arch Linux).

**Comment by eoyilmaz** [comment]
As I see it is getting enabled here: https://github.com/eoyilmaz/displaycal-py3/blob/main/DisplayCAL/wxReportFrame.py#L864

You can workout the conditions that it is getting enabled and check if it is making sense to see it enabled?

**Comment by eoyilmaz** [comment]
this is not a problem anymore... closing...
