### ISSUE TITLE
Profile deletion popup is improperly sized

### ISSUE THREAD

**Issue by ledoge** [eoyilmaz/displaycal-py3#179]
When clicking the trash can icon next to the Settings dropdown to delete the current profile, the contents of the popup are not visible due to it getting expanded to fit the list of files.
Screenshot:
![2022-09-11_23-52](https://user-images.githubusercontent.com/8040316/189550393-aa897b7b-d990-4f1c-87ea-20e6303f3c58.png)

**Comment by eoyilmaz** [comment]
Fixed in 3d9bfd4
