### ISSUE TITLE
Replace the ``DisplayCAL.ordereddict.OrderedDict`` with the Python 3 ``dict``

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#18]
Replace the ``DisplayCAL.ordereddict.OrderedDict`` with the real thing. The documentation of the ``DisplayCAL.ordereddict.OrderedDict`` says that it is compatible with Python 3 version with some additions. So it should be relatively easy to replace it.

**Comment by kamikaze** [comment]
btw simple dicts are ordered since 3.7 https://www.blog.pythonlibrary.org/2018/02/27/python-3-7-dictionaries-now-ordered/

**Comment by eoyilmaz** [comment]
Oh that's cool, I didn't know that. So, we can directly use ``dict`` and let's make it clean and remove other extra methods  that ``DisplayCAL``s version of ``OrderedDict`` was added and replace any calls to those methods.

I was waiting for rhe system to fully work before doing that kind of modifcations. But that should be fine.

I'm currently working on ``ICCProfile.Text`` and trying to figure out the best way to implement it. It is currently deriving from ``ICCProfileTag``, ``UserString`` and ``str`` (which I believe was ``unicode`` before ``2to3`` did its work on the previous repository). ``UserString`` and ``str`` are basically the same thing so I removed ``str``. But I believe it should be derived from ``bytes`` and add a ``data`` method to give the required interface.

**Comment by eoyilmaz** [comment]
The original developer used the slicing function of the ``DisplayCAL`` version of the ``OrederedDict`` very much. I think this is the challenging part. We either need to completely remove/replace the code that depends on the slicing or keep the ``OrderedDict``, which is already deriving from the ``dict``, and remove any functionality that is already covered by the native ``dict``.

**Comment by eoyilmaz** [comment]
I'm nearly done with this issue.

I've replaced ``OrderedDict`` with Python standard ``dict`` and added ``DisplayCAL.util_dict`` that has the ``dict_slice()`` and ``dict_sort()`` utility functions, which were the most used ones. Also there is a weird way of attribute lookup in ``ADict`` and ``AODict`` classes in ``DisplayCAL.ICCProfile``, I think I fixed them too.

But now we have some other issue. So expect to have a number of new issues related to this move.

**Comment by eoyilmaz** [comment]
Okay, it is done. All tests are passing. So the functionality should be the same as before this commit. But beware that there may be a tone of new bugs, which I don't have encountered though. Profiling is working... But anyway, there could be new bugs introduced with this commit.
