### ISSUE TITLE
Buttons visually get "stuck"

### ISSUE THREAD

**Issue by ledoge** [eoyilmaz/displaycal-py3#180]
This is just a minor visual bug, but I noticed that some buttons, such as the ones next to the Settings dropdown or the one for the Visual whitepoint editor, get "stuck". After clicking them, their appearance stays the same as if I was hovering over them. This also happens when holding click on one of those buttons, dragging away, and then releasing (which does not trigger the button). Weirdly, after clicking around for a bit, this bug briefly went away.

Screenshot (taken after clicking on "Profile information" and having closed the window):

![2022-09-12_00-02](https://user-images.githubusercontent.com/8040316/189550701-5deb4900-336a-47a1-8366-017ccdef4923.png)

**Comment by eoyilmaz** [comment]
I looked that when you reported that back in September and I confirm that the behavior is as you explained. But I'm not sure when I can look in to this, maybe in the future when I clean up most of the issues :) but in anyways thank you very much for reporting :+1:
