### ISSUE TITLE
Elements using AuiNotebook tend to crash

### ISSUE THREAD

**Issue by p5k369** [eoyilmaz/displaycal-py3#187]
Tabs are not correctly drawn. That part can easily be fixed in DisplayCal. However the AuiNotebook class of the auibook module of wxpython has some methods which return values other classes and methods can't handle.
In our case for example the `CalculateNewSplitSize` method. At this point it doesnt make sense to create floats.

This is also documented here:
https://github.com/wxWidgets/Phoenix/issues/2208
https://github.com/wxWidgets/Phoenix/issues/2174

**Comment by p5k369** [comment]
The bug can be experienced for example by opening the _Profile upload_ window.

**Comment by eoyilmaz** [comment]
Hey @p5k369 I was trying to reproduce this issue but had a tone of other errors related to the ``Upload Profile...`` functionality, which I mentioned here #194. I did couple of fixes but I couldn't reproduce this error.

**Comment by p5k369** [comment]
Hey Erkan, are you using Python 3.10? I think before 3.10 this wasn't a problem.
However, even before that it made no sense to draw 0.5 pixels.

**Comment by eoyilmaz** [comment]
aah you're right, apparently I was using Python 3.9 :+1:
