### ISSUE TITLE
Error reading ICC file

### ISSUE THREAD

**Issue by cby120** [eoyilmaz/displaycal-py3#199]
Dear developer:

Hello! I'm trying to apply an existing ICC file by displaycal ver 3.9.8, on Kali 2022.3, KDE plasma platform. My ICC profile is created by windows color management. When I select my ICC profile and hit open button, python3 raises an error as follows:

```shell
local variable 'cal' referenced before assignment

Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/DisplayCAL/display_cal.py", line 17743, in load_cal_handler
        ti3_lines = [line.strip() for line in cal]
    UnboundedLocalError: local variable 'cal' referenced before assignment. 
```

These are the output from terminal: 

```shell
Loading calibration curves from file...
/usr/local/share/DisplayCAL/presets/sRGB.icc
Dispwin: Warning - new_dispwin: Expected VideoLUT depth 8 doesn't match actual 10
About to open dispwin object on the display
About to clear the calibration
About to set display to given calibration
Calibration set
About to destroy dispwin object
...ok.
Loading calibration curves of current display device profile...
/home/cby/.local/share/icc/CalibratedDisplayProfile-1.icc
Dispwin: Warning - new_dispwin: Expected VideoLUT depth 8 doesn't match actual 10
Dispwin: Warning - No vcgt tag found in profile - assuming linear
About to open dispwin object on the display
About to clear the calibration
About to set display to given calibration
Calibration set
About to destroy dispwin object
...ok.
NoneType: None
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/local/lib/python3.10/dist-packages/DisplayCAL/display_cal.py",  │
│ line 17743, in load_cal_handler                                              │
│     ti3_lines = [line.strip() for line in cal]                               │
│ UnboundLocalError: local variable 'cal' referenced before assignment         │
└──────────────────────────────────────────────────────────────────────────────┘
```

I wish to apply my ICC file for color correction. If I'm not using displaycal correctly, some hint will be really nice. If any info missing, please tell me and I'll post them asap. 

Thank you very much !

**Comment by cby120** [comment]
I guess my problem must have something to do with my ICC file. It is generated by [color management - color calibration] function provided by Windows 10. I post it here for reference: 
[CalibratedDisplayProfile-1.zip](https://github.com/eoyilmaz/displaycal-py3/files/9908438/CalibratedDisplayProfile-1.zip)

I've also checked some the code. This is where variable `cal` is being defined (starts from line 17732 in display_cal.py): 
```
if cied: 
    cal = BytesIO(cied)
else:
    targ = profile.tags.get("targ")
    from DisplayCAL.ICCProfile import Text

    if targ and isinstance(targ, Text):
        tag_data = targ.tagData
        cal = BytesIO(tag_data)
```
It's likely that my ICC profile doesn't have **CEID or targ**, and it just skips all the definition of `cal`. If my ICC file is not accessible, I suppose maybe there should be an exception? More possibly, this profile needs some other procedures to be recognized, since it works on Windows and colord-kde (recognised but unable to apply calibration due to a known issue).

**Comment by eoyilmaz** [comment]
> It's likely that my ICC profile doesn't have CEID or targ

exactly, and this has been improved with a proper error message for the user with #425.
