### ISSUE TITLE
Calibration Stuck - Noob problem?

### ISSUE THREAD

**Issue by chikko80** [eoyilmaz/displaycal-py3#212]
Hi,
maybe i am just to dumb to calibrate with that tool but for me it doesn't work.
Set everything up like in the instructions on macos (besides gtk+3 -> couldn't install via homebrew, instead installed via macports).
If i start the calibration I am stuck at this point and nothing happens:

<img width="490" alt="Screen Shot 2022-11-25 at 4 38 21 PM" src="https://user-images.githubusercontent.com/58805871/204017796-fd143eb8-03b9-4373-a81e-96eba0c22336.png">

Macos Monterey - M1 Pro
Device: Calibrite Display Plus
Calibration via webhost / detected monitor

Tried the same thing on the original displaycal -> everthing works as expected

Log when it gets stuck

```
Acquired lock file: <DisplayCAL.main.AppLock object at 0x102ca22c0>
displaycal 3.9.10 2022-11-25T19:36:13Z
Mac OS X 12.6 arm64
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
CA file /private/tmp/displaycal_venv/lib/python3.10/site-packages/certifi/cacert.pem
Faulthandler
wxPython 4.2.0 osx-cocoa (phoenix) wxWidgets 3.2.0
Encoding: utf-8
File system encoding: utf-8
Loading /Users/chikko/Library/Preferences/DisplayCAL/DisplayCAL.ini
Existing client using port 50132
Connecting to 50132...
Connection to 127.0.0.1:50132 failed: [Errno 61] Connection refused
listening
writing to lock file: port: 15411
Starting up...
SDL2: None
SDL2_mixer: None
Audio module: wx 4.2.0
Enumerating display devices and communication ports...
/Users/chikko/Library/Application Support/DisplayCAL/dl/Argyll_V2.1.2/bin
ArgyllCMS 2.1.2
Argyll has virtual display support
...ok.
Initializing GUI...

...ok.
Ready.
Setting up scripting host at 127.0.0.1:15411
Check for application update...
DisplayCAL is up-to-date.
ArgyllCMS is up-to-date.
--------------------------------------------------------------------------------
Calibrate & profile
Detecting output levels range...
--------------------------------------------------------------------------------
Session log: 0_16

Working directory:
  /
   var/
    folders/
     8z/
      9nv16vxn1357hmcrhjy550j80000gn/
       T/
        DisplayCAL-4hmvktbm/

Command line:
  /Users/chikko/Library/Application Support/DisplayCAL/dl/Argyll_V2.1.2/bin/dispread
    -v
    -K
    /private/tmp/displaycal_venv/lib/python3.10/site-
      packages/DisplayCAL/linear.cal
    -dweb:8080
    -c1
    -yn
    -X
    PFS_Phosphor_Family_31Jan17.ccss
    0_16

DisplayCAL: caffeinate started, preventing screensaver and display/system sleep - waiting for dispread (PID 7071) to exit
DisplayCAL: Starting interaction with subprocess
```

EDIT: I tried different things, i had to install latest argyllcms from  https://www.argyllcms.com/downloadmac.html - after that my monitors got detected - but there is still the same problem. I am stuck on the "Interactive display adjustment" screen.
All buttons are greyed out and i can't do anything.

**Comment by eoyilmaz** [comment]
I believe it is becasue you have wxPython 4.2.0 (not looked in to it deeply though), but I have an M1 Pro too and it works for me.

**Comment by stevewnj** [comment]
Did you start it with the terminal open for additional input? (ie, launch DisplayCal with "displaycal&")? I just installed it last night on Linux and ran DisplayCal that way, and I got command line input requests in my terminal to get me past that.

**Comment by xz-dev** [comment]
If you have multi-screen, move the window to another, and will been fixed

**Comment by eoyilmaz** [comment]
This issue is too old and was using DisplayCAL 3.9.10, we are now on 3.9.12 and 3.9.13 is going to be released soon. Closing this. Please open it again if you still have an issue with this.
