### ISSUE TITLE
 PyPI installation aborts with error (again)

### ISSUE THREAD

**Issue by starsforeveryone** [eoyilmaz/displaycal-py3#213]
When trying to install DisplayCAL on the latest Fedora 37, I'm getting the following error message:

Command: sudo pip install displaycal

Output:
```
Collecting displaycal
  Using cached DisplayCAL-3.9.10.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting build
  Using cached build-0.9.0-py3-none-any.whl (17 kB)
Requirement already satisfied: certifi in /usr/lib/python3.11/site-packages (from displaycal) (2021.10.8)
Requirement already satisfied: distro in /usr/lib/python3.11/site-packages (from displaycal) (1.7.0)
Requirement already satisfied: numpy in /usr/lib64/python3.11/site-packages (from displaycal) (1.22.0)
Requirement already satisfied: Pillow in /usr/lib64/python3.11/site-packages (from displaycal) (9.2.0)
Collecting PyChromecast
  Using cached PyChromecast-13.0.1-py2.py3-none-any.whl (62 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3y4j3r_t/wxpython_c518ab61ce2346798d23f31a3769d9c6/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-3y4j3r_t/wxpython_c518ab61ce2346798d23f31a3769d9c6/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
        File "/usr/local/lib/python3.11/site-packages/attrdict/__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "/usr/local/lib/python3.11/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.11/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

Thanks for fixing!

**Comment by p5k369** [comment]
Hey @starsforeveryone, we can't fix that.
You are failing to build wxPython on your system. There is already an issue from somebody having the same issue on fedora36, maybe you can try the suggestions made in https://github.com/eoyilmaz/displaycal-py3/issues/174#issuecomment-1239889664 and give feedback if that solved your problem.

**Comment by p5k369** [comment]
Duplicate of #174

**Comment by starsforeveryone** [comment]
Can you restrict wxPython to 4.1.1 in the pip requirements file? Since the issue seems to originate there, and no functionality is lost, we could probably get it working for everybody this way! :)

**Comment by p5k369** [comment]
@starsforeveryone if you choose to use pre-build wheels the python version you are using has to match the python version they were build for.
That doesn't seem the case here. You won't find any official wheels of _wxpython-4.2.0_ for _python-3.11_ on linux yet. You can try the wheels that I build for the ubuntu test pipelines, but I doubt they will work for you. https://wxpython.p5k.org/

It is not Displaycal that refuses to start, it's wxpython.

You're best bet is to build them by yourself and you are already half way there, try to reinstall _wxpython_ with pip and the argument `--no-cache-dir`.

> Can you restrict wxPython to 4.1.1 in the pip requirements file?

You can do that by yourself but you will not get it working that way. First, you won't find any pre-build wheels for _wxpython-4.1.1_ and _python-3.11_ and second you will not be able to build them by yourself. As far as I can tell _python-3.11_ is not comaptible with _wxpython-4.1.1_. The problems you get will be something like: https://discuss.python.org/t/python-3-11-frame-structure-and-various-changes/17895

Using _python-3.10_ would work and you are also losing no functionality.

**Comment by p5k369** [comment]
> That doesn't seem the case here.

I have to take this back. I took a look at the rpm and it seems that it is indeed build for _python-3.11_, maybe the ouptut is from another package. But it is not from DisplayCal.

**Comment by starsforeveryone** [comment]
Thanks for your help! I'll try and look into it further once I got the time.

The error message comes when typing
`displaycal`
on the GNOME-Terminal.

Complete terminal output after that:
```
Traceback (most recent call last):
  File "/home/xxxxxxx/.local/bin/displaycal", line 4, in <module>
    from DisplayCAL.main import main
  File "/home/xxxxxxx/.local/lib/python3.11/site-packages/DisplayCAL/main.py", line 27, in <module>
    raise RuntimeError(
RuntimeError: Need Python version >= 3.8 <= 3.10, got 3.11.0
```

Maybe this helps? It really looks like an error from displaycal itself?

**Comment by p5k369** [comment]
True. Change line 65 in _meta.py_ to `py_maxversion = (3, 11)`.

**Comment by starsforeveryone** [comment]
still not fixed

**Comment by Sergij-SApcPro** [comment]
I don't know if it's related, but I tried with `py_maxversion = (3, 11)` and it throwed this error:

`Traceback (most recent call last):
  File "/home/sergij/.local/lib/python3.11/site-packages/DisplayCAL/main.py", line 549, in main
    _main(module, name, app_lock_file_name)
  File "/home/sergij/.local/lib/python3.11/site-packages/DisplayCAL/main.py", line 466, in _main
    from DisplayCAL.wxwindows import BaseApp
  File "/home/sergij/.local/lib/python3.11/site-packages/DisplayCAL/wxwindows.py", line 28, in <module>
    from DisplayCAL import ICCProfile as ICCP
  File "/home/sergij/.local/lib/python3.11/site-packages/DisplayCAL/ICCProfile.py", line 51, in <module>
    from DisplayCAL import edid
  File "/home/sergij/.local/lib/python3.11/site-packages/DisplayCAL/edid.py", line 43, in <module>
    from DisplayCAL import RealDisplaySizeMM as RDSMM
  File "/home/sergij/.local/lib/python3.11/site-packages/DisplayCAL/RealDisplaySizeMM.py", line 45, in <module>
    _GetXRandROutputXID = GetXRandROutputXID
                          ^^^^^^^^^^^^^^^^^^
NameError: name 'GetXRandROutputXID' is not defined
`

**Comment by p5k369** [comment]
Hey @Sergij-SApcPro, this issue has already been fixed 2 weeks ago with these commits: https://github.com/eoyilmaz/displaycal-py3/commit/3762e7be0368484d68c4a90923672fdb0f51a5fc and https://github.com/eoyilmaz/displaycal-py3/commit/97f0c91f5855e4d21f47181ef596251eb03cb835
As you can also read here: https://github.com/eoyilmaz/displaycal-py3/issues/218

If you want to install via pip you have to apply those changes by yourself because I am not able to release and publish a pypi package nor will I push to the _main_ branch. Or you just follow our [install instructions](https://github.com/eoyilmaz/displaycal-py3#how-to-install). Make sure to checkout the _develop_ branch.

**Comment by starsforeveryone** [comment]
So this issue is fixed then and we just have to wait for a new PyPi release (or build it ourselves)? Thank you! :) I'll mark as fixed then.
