### ISSUE TITLE
Version `CXXABI_1.3.13' not found 

### ISSUE THREAD

**Issue by ttrueten** [eoyilmaz/displaycal-py3#219]
Hi there,
thank you for taking over active development, otherwise I could probably forget about my calibration. Unfortunately, on my Debian system, I can't get the thing to work.  I get I the following error displayed and ask for help:

displaycal
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7fb952118ee0>
displaycal 3.9.10 2022-12-10T11:38:54Z
debian 11 bullseye x86_64
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Faulthandler 
Traceback (most recent call last):
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/main.py", line 549, in main
    _main(module, name, app_lock_file_name)
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/main.py", line 141, in _main
    from DisplayCAL.wxaddons import wx
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxaddons.py", line 9, in <module>
    from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxfixes.py", line 27, in <module>
    import wx
  File "/home/userdirectory/.local/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/userdirectory/.local/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/userdirectory/.local/lib/python3.9/site-packages/wx/libwx_baseu-3.2.so.0)
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/main.py",    │
│ line 549, in main                                                            │
│     _main(module, name, app_lock_file_name)                                  │
│   File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/main.py",    │
│ line 141, in _main                                                           │
│     from DisplayCAL.wxaddons import wx                                       │
│   File                                                                       │
│ "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxaddons.py", line  │
│ 9, in <module>                                                               │
│     from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs   │
│   File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxfixes.py", │
│ line 27, in <module>                                                         │
│     import wx                                                                │
│   File "/home/userdirectory/.local/lib/python3.9/site-packages/wx/__init__.py", line   │
│ 17, in <module>                                                              │
│     from wx.core import *                                                    │
│   File "/home/userdirectory/.local/lib/python3.9/site-packages/wx/core.py", line 12,   │
│ in <module>                                                                  │
│     from ._core import *                                                     │
│ ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13'   │
│ not found (required by                                                       │
│ /home/userdirectory/.local/lib/python3.9/site-packages/wx/libwx_baseu-3.2.so.0)        │
└──────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/main.py", line 549, in main
    _main(module, name, app_lock_file_name)
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/main.py", line 141, in _main
    from DisplayCAL.wxaddons import wx
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxaddons.py", line 9, in <module>
    from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxfixes.py", line 27, in <module>
    import wx
  File "/home/userdirectory/.local/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/userdirectory/.local/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/userdirectory/.local/lib/python3.9/site-packages/wx/libwx_baseu-3.2.so.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/debughelpers.py", line 77, in handle_error
    from DisplayCAL.wxaddons import wx
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxaddons.py", line 9, in <module>
    from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs
  File "/home/userdirectory/.local/lib/python3.9/site-packages/DisplayCAL/wxfixes.py", line 27, in <module>
    import wx
  File "/home/userdirectory/.local/lib/python3.9/site-packages/wx/__init__.py", line 12, in <module>
    __version__ = wx.__version__.VERSION_STRING
AttributeError: partially initialized module 'wx' has no attribute '__version__' (most likely due to a circular import)
Warning: handle_error(): partially initialized module 'wx' has no attribute '__version__' (most likely due to a circular import)
Exiting displaycal

Cheers,
Thomas

**Comment by p5k369** [comment]
Hey @ttrueten can you provide output from: `pip show wxpython` ?

**Comment by ttrueten** [comment]
Name: wxPython
Version: 4.2.0
Summary: Cross platform GUI toolkit for Python, "Phoenix" version
Home-page: http://wxPython.org/
Author: Robin Dunn
Author-email: robin@alldunn.com
License: wxWindows Library License (https://opensource.org/licenses/wxwindows.php)
Location: /home/tht/.local/lib/python3.9/site-packages
Requires: numpy, pillow, six
Required-by: DisplayCAL

**Comment by p5k369** [comment]
Ok technically this combination of python and wxpython works.
I'm down to guessing. Maybe you can describe how you installed displaycal? It does not look like youre using a virtual environment. Maybe there is a mismatch between an installation in a virtual environment and running Displaycal without it.
Maybe you are using a pre-build package from a different machine which does not work with your systems libstdc++? Try `strings /lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI` and see which versions are supported. 
Or your LD_LIBRARY_PATH is not pointing to the right path could also be possible, did you altered it manually recently?

**Comment by ttrueten** [comment]
Ok, these versions are supported here. Exactly the required version is not included, therefore probably the error message:

strings /lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_1.3.10
CXXABI_1.3.11
CXXABI_1.3.12
CXXABI_TM_1
CXXABI_FLOAT128

**Comment by ttrueten** [comment]
After an update to the libstdc++-11-dev DisplayCal is running. Thanks for the help.

T.
