### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by colin-adams** [eoyilmaz/displaycal-py3#228]
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tskvatmw/wxpython_2d4f087d65994810bc471c67ecdab6e9/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-tskvatmw/wxpython_2d4f087d65994810bc471c67ecdab6e9/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Now displaycal is not found as a command

**Comment by colin-adams** [comment]
I pip installed attrdict, but now it fails with:

(displaycal_venv) [colinadams@fedora displaycal-py3]$ pip install dist/DisplayCAL-3.9.*.whl
Processing ./dist/DisplayCAL-3.9.10-cp311-cp311-linux_x86_64.whl
Requirement already satisfied: build in /home/colinadams/displaycal_venv/lib64/python3.11/site-packages (from DisplayCAL==3.9.10) (0.9.0)
Collecting certifi
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting distro
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy in /home/colinadams/displaycal_venv/lib64/python3.11/site-packages (from DisplayCAL==3.9.10) (1.24.1)
Collecting Pillow
  Using cached Pillow-9.4.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
Collecting PyChromecast
  Using cached PyChromecast-13.0.4-py2.py3-none-any.whl (62 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nf70ha7k/wxpython_0b9c478f89ab4426bc676509ad4beb9e/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-nf70ha7k/wxpython_0b9c478f89ab4426bc676509ad4beb9e/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
        File "/home/colinadams/displaycal_venv/lib64/python3.11/site-packages/attrdict/__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "/home/colinadams/displaycal_venv/lib64/python3.11/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.11/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
(displaycal_venv) [colinadams@fedora displaycal-py3]$

**Comment by p5k369** [comment]
Hey @colin-adams,
remove _attrdict_ via `pip uninstall attrdict`
and install _attrdict3_. `pip install attrdict3`
Afterwards _wxpython 4.2.0_ should build fine. The sad thing is that you don't even need attrdict. I think this is a windows dependency that gets pulled regardless which os one is using. It is already fixed in the master branch as far as I can tell but it will take some time until the patched _pypi_ package is released.
See https://github.com/wxWidgets/Phoenix/issues/2225

If you do that you will get a different error message. That is because you are using _python 3.11_. The _pypi_ package of _displaycal_ will not run with _python 3.11_ unless you do a little manual tinkering or you just clone the _develop_ branch which runs fine with _python 3.11_.

**Comment by colin-adams** [comment]
I was already using develop (I should have said).
Works now. Thanks.
