### ISSUE TITLE
Is there are way to install in centos7?

### ISSUE THREAD

**Issue by shinkm1104** [eoyilmaz/displaycal-py3#230]
Hi.
I was trying to install DisplayCAL in centos7 but failed long time
I have a error in cmd `pip install wxPython==4.1.1`
and my error log is `Command '/path/to/displaycal/displaycal_venv/bin/python" -u build.py build' failed with exit code 1.`

I think this is caused by wxPython supporting centos7 to python 3.6
(And this is the last version supported by centos7. wxPyhon-4.1.1-cp36)

but I really want use this great software in centos7
How can I solve this??

**Comment by p5k369** [comment]
Hey @shinkm1104, can you please provide a full log? The message you provided only states that an error occured. Not which.
Also note that in order to run displaycal you will need python 3.8+

**Comment by eoyilmaz** [comment]
we do not support anything lesser than Python 3.8, sorry.
