### ISSUE TITLE
displaycal doesn't get installed to /usr/local/bin

### ISSUE THREAD

**Issue by Ardy123** [eoyilmaz/displaycal-py3#234]
I followed the instructions from the README.md and I had to manually execute the following command to get it to work
```sudo cp ./DisplayCAL/__main__.py /usr/local/bin/displaycal```

The installer should do this automatically.

**Comment by eoyilmaz** [comment]
The README explains how to install it under an virtulenv and not system wide. Your complain/request is invalid.
