### ISSUE TITLE
Still problems installing on Mac. Macbook Air M2 16gb 512

### ISSUE THREAD

**Issue by avemario** [eoyilmaz/displaycal-py3#246]
got this 

marioav@MBAM216512MAV ~ % pip install DisplayCAL
Collecting DisplayCAL
  Using cached DisplayCAL-3.9.10.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting build (from DisplayCAL)
  Using cached build-0.10.0-py3-none-any.whl (17 kB)
Collecting certifi (from DisplayCAL)
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting distro (from DisplayCAL)
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
Collecting numpy (from DisplayCAL)
  Using cached numpy-1.24.2-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Collecting Pillow (from DisplayCAL)
  Using cached Pillow-9.5.0-cp311-cp311-macosx_11_0_arm64.whl (3.1 MB)
Collecting PyChromecast (from DisplayCAL)
  Using cached PyChromecast-13.0.7-py2.py3-none-any.whl (62 kB)
Collecting Send2Trash (from DisplayCAL)
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting wxPython (from DisplayCAL)
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/my/j275hf7j17v0jj99zcwzn79c0000gn/T/pip-install-lwllbo69/wxpython_bc14ad48d51e400394c596e68dfc01db/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/my/j275hf7j17v0jj99zcwzn79c0000gn/T/pip-install-lwllbo69/wxpython_bc14ad48d51e400394c596e68dfc01db/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by avemario** [comment]
> This reminds me happening something similar on my Linux box. One package has been missing, and I bet it was `attrdict`. Try `pip install attrdict`.

Thank you for your answer. Could you please explain how to do that? I am not it person and have lack of the knowledge about all this coding in terminal.

**Comment by eoyilmaz** [comment]
I don't understand why `attrdict` is causing a problem, we are using `attrdict3`. Maybe it is a dependency of `wxWidgets`.

**Comment by eoyilmaz** [comment]
@hadrabap good tutorial by the way 👍

**Comment by maxwxyz** [comment]
not possible to install according to the above mentioned how-to.
I get an error on pip build:
```
clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=13.0'
error: command '/usr/bin/clang' failed with exit code 1
```
and trying to install
`zsh: no matches found: dist/DisplayCAL-3.9.*.whl`

**Comment by eoyilmaz** [comment]
@maxwxyz did you try installing it in the "normal" way?

**Comment by maxwxyz** [comment]
yes, also errors while building.

**Comment by eoyilmaz** [comment]
did you try DisplayCAL 3.9.12?

**Comment by maxwxyz** [comment]
@eoyilmaz yes, thanks for the ping. This version works!

**Comment by eoyilmaz** [comment]
Thank you, closing this then 👍
