### ISSUE TITLE
exploration of pgenerator support

### ISSUE THREAD

**Issue by 24fpsDaVinci** [eoyilmaz/displaycal-py3#247]
im wondering if this is even necessary,  do consumer laptops already have bit accurate RGB hdmi output (eg latest macbook pros)? I did notice HCFR has support for pgen.

the first of several relevant commit in hcfr
https://github.com/arthur-liberman/hcfr-code/commit/c266f4f9db76ba9e8eecdefcabc28a6eb874cf55

at avsforum i was able to find this
https://www.avsforum.com/threads/the-cheap-test-pattern-generators-accuracy-thread.3023002/page-53

 "Surprisingly, the HDMI output of my laptop resulted bit accurate!!!"

another interesting question is, will running displaycal/argyll directly on the raspberry pi hardware produce the same accuracy

**Comment by quietvoid** [comment]
PGenerator communicates with TCP/IP.
DisplayCAL does have generic TCP/IP code but it would need to be implemented.

I started some work on it here: https://github.com/quietvoid/pgen_client, and I was planning on tying to add it to DisplayCAL but kinda lost interest.
