### ISSUE TITLE
Installation issues with Mint 21.1 (Ubuntu variant) - solution inside

### ISSUE THREAD

**Issue by philpem** [eoyilmaz/displaycal-py3#248]
First, thanks for all the hard work in getting DisplayCAL working on Python 3 :)

To be clear -- I'm using the `develop` branch.

I installed DisplayCAL on Mint 21.1 and had a few issues. I'm documenting this here as I also found solutions to those issues :)

* The `python` and `pip` executables on recent Ubuntu derivatives (i.e. Mint 21.1 which is based on Ubuntu Jammy) are called `python3` and `pip3` respectively.
* wxPython installation won't complete unless the `attrdict3` package is manually installed with `pip3` before feeding the `requirements.txt` to it. (see https://github.com/wxWidgets/Phoenix/issues/2225#issuecomment-1209569516 for more on this)

Once that's sorted, DisplayCAL installs and works wonderfully on Mint 21.1.

I imagine this might help if you wanted to use `sudo pip3 install DisplayCAL` to install DisplayCAL system-wide, but 

Hopefully this helps anyone who's trying to get DisplayCAL working on Mint or Ubuntu

This might help with: #213, #235, #242.

This solution is actually buried in the comments on #242 (https://github.com/eoyilmaz/displaycal-py3/issues/242#issuecomment-1473937991) but isn't obvious. Could the README be updated to account for the above, and all these duplicate tickets merged into one?

**Comment by p5k369** [comment]
This is not a solution. A solution would be if the fix (which was already committed) would be released. 
What we are talking about is a workaround that forces you to install a dependency (which, on linux, is not needed by 
neither displaycal nor wx-python).
This is the commit that needs to be released https://github.com/wxWidgets/Phoenix/commit/2e9169effa9abf14f34f8436a791b8829eea7774

#213, #235, #242 are all closed or fixed as far as I can tell.

**Comment by Quppa** [comment]
Does this work with Python 3.11 as well, or am I being obtuse?

Regardless of whether I install `attrdict3` in advance, I can't get past `ModuleNotFoundError: No module named 'attrdict'`. I'm using the `develop` branch.

```
Collecting attrdict3 (from -r requirements.txt (line 1))
  Downloading attrdict3-2.0.2-py2.py3-none-any.whl (10 kB)
Collecting build (from -r requirements.txt (line 2))
  Downloading build-0.10.0-py3-none-any.whl (17 kB)
Collecting certifi (from -r requirements.txt (line 3))
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 6.2 MB/s eta 0:00:00
Collecting dbus-python (from -r requirements.txt (line 4))
  Downloading dbus-python-1.3.2.tar.gz (605 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 605.5/605.5 kB 13.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting distro (from -r requirements.txt (line 5))
  Downloading distro-1.8.0-py3-none-any.whl (20 kB)
Collecting numpy (from -r requirements.txt (line 6))
  Downloading numpy-1.24.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 14.4 MB/s eta 0:00:00
Collecting Pillow (from -r requirements.txt (line 7))
  Downloading Pillow-9.5.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 14.1 MB/s eta 0:00:00
Collecting PyChromecast (from -r requirements.txt (line 8))
  Downloading PyChromecast-13.0.7-py2.py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 6.4 MB/s eta 0:00:00
Collecting Send2Trash (from -r requirements.txt (line 9))
  Downloading Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting wxPython>=4.1.1 (from -r requirements.txt (line 10))
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 12.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/quppa/displaycal_venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/quppa/displaycal_venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/quppa/displaycal_venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2nbjtl2e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2nbjtl2e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2nbjtl2e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2nbjtl2e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "/tmp/pip-install-lcm2u_p6/wxpython_d4978c78f8e74888bfa6ae18b0aa2dfd/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

If I run `pip install attrdict3` beforehand, only the first line changes:
```
Requirement already satisfied: attrdict3 in /home/quppa/displaycal_venv/lib64/python3.11/site-packages (from -r requirements.txt (line 1)) (2.0.2)
```

**Comment by p5k369** [comment]
Hey @Quppa, your log is incomplete and the output is not enough to tell what you really did. If I had to guess, I would say a former installation has gone wrong and now it always fails because the cache did not get cleaned up. (but I could also be wrong) 

Remove everything. Run `pip install attrdict3`. Try: `pip install wxPython --no-cache-dir`. 

An alternative would be to delete the import of AttrDict in _Phoenix/buildtools/config.py_ before building the wxPython wheels, you do not need it anyway.

This issue is not related to displaycal or python-3.11. It is an issue that everybody that tries to build wxPython-4.2.0 wheels on linux will experience. It's already patched out but does not get released.

**Comment by Quppa** [comment]
Thanks @p5k369 - starting over fixed it.

Start to finish, I ran:
```
git clone https://github.com/eoyilmaz/displaycal-py3
python -m venv ./displaycal_venv
source ./displaycal_venv/bin/activate
cd ./displaycal-py3/
git checkout develop
pip install -r requirements.txt
python -m build
pip install dist/DisplayCAL-3.9.*.whl
```

Sorry you're stuck doing support for wxPython. It's very strange that they won't cut a release that includes the patch.

**Comment by eoyilmaz** [comment]
closing this as this seems to be unrelated to DisplayCAL and kind of solved.

**Comment by eoyilmaz** [comment]
strangly I'm getting this error on an Windows 11 arm64 virtual machine running on MacOS.
