### ISSUE TITLE
Build doesn't work offline

### ISSUE THREAD

**Issue by hfiguiere** [eoyilmaz/displaycal-py3#252]
The setup seems to require to download stuff of the internet.

$  python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools)

In a sandboxed envirnoment with no network it fails.

However setuptools = 67.6.1 is install.

This sandboxed environment is for flatpak builds. (see #232)

**Comment by hfiguiere** [comment]
The solution is to pass `--isolation`

**Comment by eoyilmaz** [comment]
closing this
