### ISSUE TITLE
argyll-targen hangup with a true black display with auto-optimized patchset above 175 patches.

### ISSUE THREAD

**Issue by MCPO-Spartan-117** [eoyilmaz/displaycal-py3#266]
- Distro:                                 `Gentoo`
- Python:                               `3.11.4`
- DisplayCAL:                         `3.9.11`
- Argyllcms:                          `2.3.1-r1`
- Display:                              `Alienware AW3423DWF`
- Display Panel:                   `QD-OLED`
- Output Levels:                  `0-255`, `16-235`
- Colorimeter:                       `Rite-x Display Plus` in `Contact Mode`
- Colorimeter Driver:           `i1 DisplayPro, ColorMunki Display`
- Colorimeter Correction:   `Dell, AW3423DWF DCI-P3 (il Pro 2)`
- Observer:                          Both `CIE 1931 2` and `CIE 2012 2`
- Dispread and Spotread Args:  `-Q2012_2`
- White level drift:               on and off
- Black level drift:                on and off
- Calibration Settings:        All set to `as measured`
- Profile Type:                     `XYZ LUT + matrix`, `XYZ LUT` and `L*a*b* LUT`
- Blackpoint compensation:  on and off
- Profile Quality:                 `high`, `medium` and `low` 
- Tested Whitepoint Nits:  `1-100`
- Tested Blackpoint Nits:   `0-0.24`

`argyll-targen` is unable to compute the last 100-300 patches with a true black display with auto-optimized above 175 patches.

Normal terminal output doesn't say anything is wrong.

Output of manually invoking `argyll-targen` with the provided arguments from `DisplayCAL` and `-v 4`, it spams the last line for 200000+ lines in a span of 2 seconds.
`argyll-targen -v 4 -d3 -e4 -s29 -g85 -m0 -f1121 -A1.0 -G -N0.5 -B4 -b0 -V1.6 -c 'AW3423DWF #1 2023-06-13 10-19 F XYZLUT+MTX.icc' 'AW3423DWF #1 2023-06-13 10-19 F XYZLUT+MTX'`
[targen.log](https://github.com/eoyilmaz/displaycal-py3/files/11736297/targen.log)

Upping the Blackpoint to `0.24` and Whitepoint to `2.5` (by using color offsets) allows it to complete.

Changing `-V1.6` argument to `-V1.0` allows it to complete, tried making the value lower and higher with the same hangup.

**Comment by eoyilmaz** [comment]
I'm closing this old issue as this should be related to ArgyllCMS. Did you try the latest version (3.1.0)?

**Comment by MCPO-Spartan-117** [comment]
This is still an issue with `3.1.0`, i was going to post on their mailing list about this but i haven't found the time to do so.

**Comment by eoyilmaz** [comment]
@MCPO-Spartan-117 what is `3.1.0`?

**Comment by MCPO-Spartan-117** [comment]
No longer a issue as of `3.3.0`.
https://www.freelists.org/post/argyllcms/Targen-argument-V101-hangs-with-true-black-display

**Comment by eoyilmaz** [comment]
Good to know thank you.
