### ISSUE TITLE
Fix URL at "About"

### ISSUE THREAD

**Issue by Korb** [eoyilmaz/displaycal-py3#280]
https://github.com/eoyilmaz/displaycal-py3

> About
> DisplayCAL Modernization Project
> eoyilmaz.github.io/displaycal-py3/ 

> 404
> There isn't a GitHub Pages site here.
> If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.
> GitHub Status — @githubstatus
>

**Comment by p5k369** [comment]
already requested here: #233
