### ISSUE TITLE
Generated report for profile verification doesn't contain the desired data

### ISSUE THREAD

**Issue by aufkrawall** [eoyilmaz/displaycal-py3#285]
Hello once again :) ,

on Windows with older DisplayCal build, the verification tab looks like this with Rec709 simulation profile and "use simulation profile as display profile" checkbox ticked:
![displaycalverwin](https://github.com/eoyilmaz/displaycal-py3/assets/13510490/6ac8bbfa-090a-4c05-8929-d68053b3a92d)

After running the verification, a report is generated that contains the desired data, like single color or gamma curve deviations compared to the selected ICC profile:
[Measurement Report 3.8.9.3 — G27q-20 @ 0, 0, 2560x1440 — 2023-07-29 16-44.zip](https://github.com/eoyilmaz/displaycal-py3/files/12207434/Measurement.Report.3.8.9.3.G27q-20.%40.0.0.2560x1440.2023-07-29.16-44.zip)

On Linux with displaycal-py3 (latest build from Arch repository), verification tab looks like this (the second profile selection section close to the bottom looks a bit weird to me in comparison to Windows):
![Screenshot_20230729_170521](https://github.com/eoyilmaz/displaycal-py3/assets/13510490/753efc60-ad9e-4980-9673-8b93952ab439)

When running the verification process with the Linux build, the generated report is missing (shows just 0, which is wrong) the desired data for deviation of colors, gamma etc.:
[Measurement Report 3.9.11 — G27q-20 @ 0, 0, 2560x1440 — 2023-07-29 16-39.zip](https://github.com/eoyilmaz/displaycal-py3/files/12207443/Measurement.Report.3.9.11.G27q-20.%40.0.0.2560x1440.2023-07-29.16-39.zip)

![colval](https://github.com/eoyilmaz/displaycal-py3/assets/13510490/0c894e4a-a80f-4cf2-a522-4644d4bc3a60)

displaycal-py3 should report the same values in the generated report like the Windows version does.
Thanks!

Attached profile in case it could  be useful for reproduction steps:
[G27q-20 #1 2023-03-13 23-08 D6500 Rec. 1886 M-S 3xCurve+MTX.zip](https://github.com/eoyilmaz/displaycal-py3/files/12207448/G27q-20.1.2023-03-13.23-08.D6500.Rec.1886.M-S.3xCurve%2BMTX.zip)

**Comment by p5k369** [comment]
Hey @aufkrawall this seems like a duplicate of #276 which should already be fixed in #278

**Comment by aufkrawall** [comment]
Thanks, I guess I overlooked this since the Arch package update took a few weeks since then. I'll close then and re-open in case something's still off with the next version.
