### ISSUE TITLE
Windows Binary Paid Support

### ISSUE THREAD

**Issue by coolrecep** [eoyilmaz/displaycal-py3#293]
Hi,

We would like to support the developer to have an installable Windows version. Would you accept it? If yes, what would be the cost?

Regards

**Comment by Eckoa** [comment]
The version from the displaycal website should work just fine on windows. 

I may be wrong but I don't think this has any additional features except that linux user can actually install/build it since Python 2 has been dropped most everywhere.

**Comment by coolrecep** [comment]
Unfortunately, no. We are having problems with the Windows version.

**Comment by eoyilmaz** [comment]
Any Windows related issue should be fixed with #312 now.
