### ISSUE TITLE
10bit VCGT on Linux

### ISSUE THREAD

**Issue by Calandracas606** [eoyilmaz/displaycal-py3#294]
The VCGTs in the generated ICC profiles always appear to be 8 bits on Linux, even when created for a 10bit display

The 8 bit VCGTs are unable to be applied to a 10 bit display by dispwin, xcalib, or xiccd

Not sure if 10 bit VCGTs are possible at all, maybe this is a linux limitation.

If this is not a limitation, having an option to force the generation of 10bit VCGT would be very useful

**Comment by janos666** [comment]
The .cal 3x1DLUT files are 8 bit input, 16 bit output files on Windows as well. ArgyllCMS's dispcal goes through 96 samples at it's highest setting.

**Comment by eoyilmaz** [comment]
So basically Florian says:

> The number of entries (usually 256) is not indicative of gamma table bit depth
(afaik), if that is what you're judging it by. Also, dispcalGUI's curves
window will always calculate and view values based on 8-bit depth, as it is
not possible to know the actual bit depth without measurements (and even then
there would be margin for error). But graphics hardware with 10-bit gamma
table support will (should) do the right thing,

**Comment by VgerTest** [comment]
Maybe you need proprietary AMD/nv driver instead of GNU to use 10bit VCGT

**Comment by eoyilmaz** [comment]
Regarding my last comment I think we can close this one, as this is not an issue with DisplayCAL...
