### ISSUE TITLE
Can't install the profile after calibration ("sudo timeout")

### ISSUE THREAD

**Issue by Fob-io** [eoyilmaz/displaycal-py3#296]
Hi, this is the first time using this Py3 version of display cal on my Mac (running the latest MacOS Sonoma), at the end of the calibration I inserted the authentication, and this "sudo timeout" showed up after a few seconds.

Does anyone have a solution?
![image](https://github.com/eoyilmaz/displaycal-py3/assets/82308758/c1e67b0d-4d26-4198-87fc-9042da0523b1)

**Comment by Anonym-w** [comment]
i have the same problem

**Comment by Fob-io** [comment]
@eoyilmaz any news on this problem ?

**Comment by Fob-io** [comment]
@Anonym-w just found a workaround, use this path in the Name File before starting calibration 

`%dns-%Y-%m-%d %H-%M`

**Comment by FlorinAndrei** [comment]
@Fob-io the workaround is not clear. Where do I need to put that string?

**Comment by Fob-io** [comment]
@FlorinAndrei in the profiling tab
![Screenshot 2024-08-19 alle 11 18 08](https://github.com/user-attachments/assets/44b520c8-634a-41c2-a649-803f2a6a8818)

**Comment by eoyilmaz** [comment]
@Fob-io I don't think changing to a shorter profile name solves the issue, as I see that the `sudo` command really is getting timed out.

**Comment by eoyilmaz** [comment]
Found the problem and fixed it...
