### ISSUE TITLE
Start up issue on m2 Mac

### ISSUE THREAD

**Issue by 1jadas** [eoyilmaz/displaycal-py3#300]
/Users/macbook-kjs/DisplayCAL-3.9.11/scripts/displaycal ; exit;
macbook-kjs@Macbook-Pro---KJS ~ % /Users/macbook-kjs/DisplayCAL-3.9.11/scripts/displaycal ; exit;
Traceback (most recent call last):
  File "/Users/macbook-kjs/DisplayCAL-3.9.11/scripts/displaycal", line 4, in <module>
    from DisplayCAL.main import main
ModuleNotFoundError: No module named 'DisplayCAL'

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by MStraeten** [comment]
how did you install it? Which version? Did you follow https://github.com/eoyilmaz/displaycal-py3#how-to-instal ?
At least current master works fine on m1

**Comment by eoyilmaz** [comment]
I don't think that this is correctly installed...
