### ISSUE TITLE
macOS: DisplayCal Menu disappears after profiling

### ISSUE THREAD

**Issue by MStraeten** [eoyilmaz/displaycal-py3#303]
build and run main branch of Displaycal on macOS Sonoma + macports according to the description in https://github.com/eoyilmaz/displaycal-py3#how-to-install

everything is fine but after finishing profiling the DisplayCal Mneu disappears (just a Python menu remains)
any idea how to get this back (except restarting DisplayCAL)?

**Comment by hyperknot** [comment]
It's exactly the same for me as well. Any time using the instruments makes the menu almost empty. I mean almost, because Settings for example is still present.

**Comment by eoyilmaz** [comment]
I confirm this... let's see what is wrong

**Comment by eoyilmaz** [comment]
Fixed with bc6552b

**Comment by hyperknot** [comment]
Thanks a lot!!
