### ISSUE TITLE
ArgyllCMS: Dispwin: Error We don't have access to the VideoLUT for clearing

### ISSUE THREAD

**Issue by hendkai** [eoyilmaz/displaycal-py3#305]
System: Ubuntu 22.04.3 LTS

I can calibrate successfull but i can't activate the profile.
ArgyllCMS: Dispwin: Error We don't have access to the VideoLUT for clearing
This happens when i try to install the Profile.

![Bildschirmfoto vom 2023-11-26 20-53-17](https://github.com/eoyilmaz/displaycal-py3/assets/53811546/83658a8b-b5f8-4475-99ab-91a959a6e492)

Thanks and great tool!

**Comment by eoyilmaz** [comment]
Did you try installing to the user or as system wide (which should require root access)?

**Comment by keantoken** [comment]
I had a problem where Xcalib would work but dispwin could not access the VCGT. It seemed to work after using the ARGYLL_IGNORE_XRANDR1_2 environment variable. It is mentioned here:

https://www.argyllcms.com/doc/dispwin.html

**Comment by hendkai** [comment]
Thanks for the answer. Cant reproduce it because i switched to bazzite.

**Comment by eoyilmaz** [comment]
Thank you, closing the issue then 👍

**Comment by Mierscheid** [comment]
> I had a problem where Xcalib would work but dispwin could not access the VCGT. It seemed to work after using the ARGYLL_IGNORE_XRANDR1_2 environment variable. It is mentioned here:
> 
> https://www.argyllcms.com/doc/dispwin.html

I see a wasteland of text with content that is incomprehensible to me. How does this help me if I have exactly the same error?

**Comment by keantoken** [comment]
Unless you can use ArgyllCMS yourself by script or console, the most you can do is submit an issue requesting that DisplayCal include the already existing option from ArgyllCMS. Do what you can reasonably do and then waste no more energy...

And keep in mind this is only a potential solution, it's not guaranteed to solve your problem.

**Comment by Mierscheid** [comment]
I assume that I cannot create a profile under Windows with the Datacolor software that I can then import in Ubuntu (Settings->Colours)?
