### ISSUE TITLE
Show calibration curves from video card blanks display

### ISSUE THREAD

**Issue by hyperknot** [eoyilmaz/displaycal-py3#313]
If I click "Show calibration curves from video card" in the curves view dialog, it blanks my full screen. There is no way to get out of this, unless trying some crazy keyboard combinations, like Cmd + Q or Ctrl + Cmd + Q to lock user.

**Comment by eoyilmaz** [comment]
Yeah this happens to me on random other places... I'm on it...

**Comment by eoyilmaz** [comment]
This is most probably related to ArgyllCMS + MacOS... I updated to ArgyllCMS 3.1.0 and observing it to see if it will happen with it too...

**Comment by eoyilmaz** [comment]
I think I'm not getting this anymore, please try updating to ArgyllCMS 3..1.0 and report back if you are still having this issue. Closing this now... re-open if required.

**Comment by MStraeten** [comment]
unfortunately i'm getting this occasionally but without discernible regularity with 3.9.12 installed via pypi as well as a custom build of develop branch and using argyllcms 3.2.0

**Comment by eoyilmaz** [comment]
This is related to ArgyllCMS, and happens even when running:

```shell
dispwin -d1 -L
```

So it needs to be reported [ArgyllCMS](https://www.argyllcms.com/mailinglist.html)
