### ISSUE TITLE
Measurement reports

### ISSUE THREAD

**Issue by jsalexjs** [eoyilmaz/displaycal-py3#314]
Hi,

I'm having an issue with the verification phase of the software. When I look at my complete measurement report, all of the delta averages are measured at zero (which is obviously not possible).

Thanks!

**Comment by jsalexjs** [comment]
Has anyone had an accurate report?

**Comment by p5k369** [comment]
Hey @jsalexjs is the issue you are describing comparable with #276 ? And which version of diplaycal are you running, the main branch?

**Comment by jsalexjs** [comment]
> Hey @jsalexjs is the issue you are describing comparable with #276 ? And which version of diplaycal are you running, the main branch? 

Hi yes main branch, 3.9.11. Installed through up to date pip. Python also up to date. Sonoma 14.2.1, m1 Mac Studio and m2 pro Mac mini.

Not same issue as #276, my reports are basically blank as if they haven't got any data from the measurements.

**Comment by p5k369** [comment]
Maybe its not the exact same issue and it looks more like #285 or #295 . However this is fixed in the develop branch. Note that one user mentioned being not able to run develop with macos. https://github.com/eoyilmaz/displaycal-py3/issues/295#issuecomment-1890026197
Maybe it is some mac os specific error, I can not verify this.

**Comment by jsalexjs** [comment]
Ok I'll try this and report back 👍🏻

**Comment by eoyilmaz** [comment]
I checked #295 and this is working for me on my Macbook Pro. I'll release 3.9.12 soon, closing this, please open it again if you think it is not solved for you.

**Comment by eoyilmaz** [comment]
3.9.12 is released please try it.
