### ISSUE TITLE
Add note to README to explain development happens on the "develop" branch

### ISSUE THREAD

**Issue by philpem** [eoyilmaz/displaycal-py3#316]
This is very much a "me, in a hurry" problem - so my apologies in advance if this comes across as a bit of a nitpick.

I was having a conversation with a friend earlier, and they commented that "even the Python3 fork of Displaycal is dead". Sure enough, I looked, read the first part of the README (last release in 2022), and it seemed like he was right. There were also no merges to master in 8 months.
I fired up the Network view (on the Insights tab) to try and active fork, and saw some merges from a few days ago... onto the "develop" branch, which was very much active.

My proposal is that maybe something could be added near the top of the `README.md` or project description to explain that most of the development happens on the "develop" branch.
This is useful information for both users and prospective contributors: as a user, you know to check the "develop" branch for activity, and as a developer, you know to target your PRs to that branch.

Many thanks for all your hard work maintaining this - I've been using DisplayCal for years, and it's great to see it's still being actively maintained and improved.

**Comment by eoyilmaz** [comment]
We already mention the `develop` branch in [How To Install](https://github.com/eoyilmaz/displaycal-py3?tab=readme-ov-file#how-to-install) section...
