### ISSUE TITLE
Installation issue on windows

### ISSUE THREAD

**Issue by dkflint723** [eoyilmaz/displaycal-py3#334]
I'm consistently getting the same error when trying to install via PyPi on windows 11.

ValueError: path '/Users/eoyilmaz/Documents/development/displaycal-py3/CHANGES.html' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by eoyilmaz** [comment]
oh interesting, am I burrying something in to the wheel or tar.gz files that is special to my configuration? Let me look into this.

**Comment by eoyilmaz** [comment]
It seems that the `DisplayCAL.egg-info/SOURCES.txt` contains some duplicate entries with absolute paths.

**Comment by eoyilmaz** [comment]
Found the source of the problem and this should be fixed in the next release (3.9.13).
