### ISSUE TITLE
Build error: RuntimeError: Need Python version >= 3.8 <= 3.11, got 3.12.2

### ISSUE THREAD

**Issue by mzdial** [eoyilmaz/displaycal-py3#335]
Excuse my little understanding on how to fix this problem. Perhaps others are having the same issue.

I've tried to force reinstall/rollback to python 3.10

brew install glib gtk+3 python@3.10

But I'm having this come up when I do the make launch:

source ./.venv/bin/activate; \
	displaycal
Traceback (most recent call last):
  File "/Users/mzdial/Downloads/displaycal-py3/.venv/bin/displaycal", line 4, in <module>
    from DisplayCAL.main import main
  File "/Users/mzdial/Downloads/displaycal-py3/.venv/lib/python3.12/site-packages/DisplayCAL/main.py", line 27, in <module>
    raise RuntimeError(
**RuntimeError: Need Python version >= 3.8 <= 3.11, got 3.12.2**
make: *** [launch] Error 1

How can I modify to make this work? Appreciate any help!

**Comment by ethanbrookins** [comment]
[This guide helped me out a while back.](https://www.cyishere.dev/blog/fix-python-break)

You just need to update your `python3` path to specify the other version. You can have multiple versions installed in `brew`.

Specifically, in step 3, set the python version number in the path to the one you want to be the working default:
`export PATH="/usr/local/opt/python@3.10/libexec/bin:$PATH"`

**Comment by eoyilmaz** [comment]
On the otherhand we should start testing DisplayCAL with Python 3.12 too.

**Comment by mzdial** [comment]
Thanks for the link! I was able to understand things a bit better. I ended up uninstalling 3.12 and rolling back to 3.10. I can get it to run now.

@eoyilmaz, Am I not understanding that this does not build a GUI MacOS executable? I found the command line binary in here: /displaycal-py3/.venv/bin/displaycal

Sorry for my lack of understanding. Not a python programmer!

> [This guide helped me out a while back.](https://www.cyishere.dev/blog/fix-python-break)
> 
> You just need to update your `python3` path to specify the other version. You can have multiple versions installed in `brew`.
> 
> Specifically, in step 3, set the python version number in the path to the one you want to be the working default: `export PATH="/usr/local/opt/python@3.10/libexec/bin:$PATH"`

**Comment by jaminmc** [comment]
I changed the max verion in the meta.py to:
`py_maxversion = (3, 12)`
and it compiles and runs fine :)

**Comment by eoyilmaz** [comment]
> I changed the max verion in the meta.py to:
> `py_maxversion = (3, 12)`
> and it compiles and runs fine :)

Yeah I'm currently testing DisplayCAL with Python 3.12 and it seems to be working fine. I'll release a new version soon that supports Python 3.12.

**Comment by Calandracas606** [comment]
Could you please make a new tagged release with this change?
