### ISSUE TITLE
Make it run under win10

### ISSUE THREAD

**Issue by p5k369** [eoyilmaz/displaycal-py3#34]
The application itself launches but there is a significant amount of windows specific code that has to be reviewed to make profiling and calibrating work.

**Comment by eoyilmaz** [comment]
I merged your PR :+1:

I think, I'll start testing it under Windows 10 soon. But my priority is to make it run under recent Linux distributions.

**Comment by fire332** [comment]
How about the possibility of using [the new Windows ICC profile extensions](https://learn.microsoft.com/en-us/windows/win32/wcs/display-calibration-mhc) which offers better accuracy, precision, and the ability to define ST.2086 HDR metadata for the display?

**Comment by cfelicio** [comment]
I'm still running 3.8.9.3 on Windows 11, but I noticed the color flickers sometimes, and also dispcalgui fails to re-apply the profile. I also use the same desktop with mpc-hc / madvr, and dispcalgui correctly disables the icc profile while madvr is active with the 3dlut. I wonder if it makes sense to update to the latest version from this branch, or wait for full windows support? Also interested on what's going to be the best practice, now that Windows seems to have improved color support, per @fire332  note above.

**Comment by fire332** [comment]
The best way to go about Windows 11 from what I've seen thus far is to take the profile made with DisplayCal, manually add the appropriate MHC2 tags, and load it with Windows's calibration loader.

See: https://github.com/dantmnf/MHC2

**Comment by cfelicio** [comment]
Umm, after reading it, I'm wondering if it's a bit too early to adopt this:

1 - Madvr / 3DLut will likely not work properly, although its likely possible to add an exception via advanced properties
2 - Apps that matter are already color managed (e.g. Photoshop), but its certainly nice to have everything color managed without having to deal with in app specifics
3 - HDR monitors do not work very well with this tech yet, even if not being used in HDR mode. The author provides some workarounds, so might still be worth a shot if you really want to adopt it

@fire332 have you tried it yet? I'm in the middle of wrapping up a project, but I'll have this flagged to do some testing later this year. In any case, pretty exciting development on color management for Windows! Appreciate the share!

**Comment by cromefire** [comment]
> The best way to go about Windows 11 from what I've seen thus far is to take the profile made with DisplayCal, manually add the appropriate MHC2 tags, and load it with Windows's calibration loader.
> 
> See: https://github.com/dantmnf/MHC2

That sounds like something that could hopefully be automated together with some native Windows HDR (or even Vulkan so it's compatible to Linux in the future?) pattern generator to get proper HDR calibration.

**Comment by p5k369** [comment]
In general possible with latest release. 
https://github.com/eoyilmaz/displaycal-py3/releases/tag/3.9.12
