### ISSUE TITLE
pytest (and DisplayCal itself) segfaults with python-3.12 on wxPython-4.2.1 import and exiting the application

### ISSUE THREAD

**Issue by p5k369** [eoyilmaz/displaycal-py3#341]
If pytest is called with python-3.12 and wxPython is imported like
`import wx`
a segmentation fault is raised after the test.

Message that might also be relevant:
```
<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.

<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.ScalarMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.

```

Edit:
It does not segfault on the import but after the test has run.
Also DisplayCal itself closes with a segfault:
`Process finished with exit code 139 (interrupted by signal 11:SIGSEGV)`

**Comment by p5k369** [comment]
Indeed there is a problem with wxPython-4.2.1 not properly supporting python 3.12 which leads to the application segfaulting after closing.
Should be fixed in next release as it is already fixed in the snapshot wxPython-4.2.2a1.dev5626.

See https://github.com/wxWidgets/Phoenix/issues/2455

**Comment by eoyilmaz** [comment]
@p5k369 do you remember why we were installing wxPython through the whl's downloaded from your website?

**Comment by p5k369** [comment]
Hey @eoyilmaz 
wxpython only provides some wheels for Ubuntu and some python versions. So we could build them in the github action, but that would take quite some time. 
But no other reason than that.

**Comment by eoyilmaz** [comment]
@p5k369 yeah the tests took around 22-23 minutes to complete each. But, let's keep it in this way to reduce the dependency on to your website.

I'm also updating the `requirements.txt` to use `wxPython>=4.2.2` for all Python versions and have another `requirements-tests.txt` for testing purposes where we are able to install `wxPython>=4.1.1` for Python 3.8-3.11 and `wxPython>=4.2.2` for Python 3.12+.
