### ISSUE TITLE
New user, eye-one display 2, DisplayCAL: Waiting for send buffer

### ISSUE THREAD

**Issue by zougloub** [eoyilmaz/displaycal-py3#350]
I discovered I had an eye-one display 2 lying around and decided to use it today with displaycal-py3, which I never used before (but I'm very familiar with color and have used argyll for cameras and scanners).

When opening the software the colorimeter is detected, and it can detect that luma variation is tiny when I leave it not on the screen, and when I put it on the screen a first batch of measurements is done, then at some point the software is hung with "DisplayCAL: Waiting for send buffer".

```
Command line:
  /usr/bin/argyll-dispcal
    -v2
    -d1
    -c1
    -yl
    -P0.5,0.5,1.5
    -qm
    -t
    -g2.2
    -f1.0
    -k0.06
    -A4.0
    'Monitor 1 2024-04-02 6% neutral 2.2 M-S LabLUT'

DisplayCAL: Starting interaction with subprocess
Setting up the instrument

Place instrument on test window.

DisplayCAL: Waiting for send buffer
DisplayCAL: Detected instrument placement (screen/spot) message
DisplayCAL: Skipping place instrument on screen message...
DisplayCAL: Send buffer received:  
DisplayCAL: Sending buffer: ' '
Hit Esc or Q to give up, any other key to continue:

Display type is 'l'

Target white = native white point

Target white brightness = native brightness

Target black brightness = native brightness

Target advertised gamma = 2.200000



Display adjustment menu:

Press 1 .. 7

1) Black level (CRT: Offset/Brightness)

2) White point (Color temperature, R,G,B, Gain/Contrast)

3) White level (CRT: Gain/Contrast, LCD: Brightness/Backlight)

4) Black point (R,G,B, Offset/Brightness)

5) Check all

6) Measure and set ambient for viewing condition adjustment

7) Continue on to calibration

8) Exit

DisplayCAL: Waiting for send buffer
```

I'm running python3.11, argyllcms 3.1.0 and displaycal-py3-3.9.10

Best regards,

**Comment by simonszu** [comment]
Same here with a Spyder 2. macOS Sonoma, Mac Mini M2.

**Comment by eoyilmaz** [comment]
can you please try with DisplayCAL 3.9.12

**Comment by simonszu** [comment]
I tried on last wednesday with the develop branch, and was successful. So, whatever changes you did in the past 2 weeks fixed it for me :)

**Comment by eoyilmaz** [comment]
Closing this as per @simonszu 's comment.
