### ISSUE TITLE
sRGB missing from "3D LUT" dropdown?

### ISSUE THREAD

**Issue by tohoku** [eoyilmaz/displaycal-py3#352]
In the SourceForge version of displaycal, I can see "sRGB" as an option in the "Source colorspace" dropdown. But in `displaycal-py3` sRGB is not included. How can I add sRGB to this list?

![displaycal-srgb](https://github.com/eoyilmaz/displaycal-py3/assets/932621/ad7b8cc8-b987-4f17-895f-ad700cfbc006)

**Comment by Techi-Joe** [comment]
I also had this issue. Make sure in display and instrument you have correction set to none, all the check boxes should be unchecked except for "override minimum display update delay" (so turn black and white compensation off), set output levels to "full range 0-255", and make sure to define the tone curve in the calibration page. After that, and option called "ITU-R BT.709 Reference Display" should pop up, which is what you want for SDR display Calibration. sRGB is only used as a colorspace reference is displaycal (somewhat confusingly), but you shouldn't calibrate to it. If that dosent work try finding a icc for a source colorspace manually and add it directly to the folder, I believe its path is called "DisplayCAL/ref/"

**Comment by tohoku** [comment]
@Techi-Joe Thank you for sharing this! I thought I was going insane. I bought a very expensive grading monitor and for some reason the verification wasn't good. It's working great now, though. Couldn't be happier.
