### ISSUE TITLE
Installation via 'make install' Does Not Work

### ISSUE THREAD

**Issue by bradleyandrew** [eoyilmaz/displaycal-py3#357]
Hello,

I followed the instruction in 'How to Install' and got this error when running 'make install':
```
source ./.venv/bin/activate; \
	pip install ./dist/DisplayCAL-3.9.12-*.whl --force-reinstall;
WARNING: Requirement './dist/DisplayCAL-3.9.12-*.whl' looks like a filename, but the file does not exist
ERROR: DisplayCAL-3.9.12-*.whl is not a valid wheel filename.
make: *** [install] Error 1
```
To fix the issue I opened the 'Makefile' in the root directory and changed this line from:
`	pip install ./dist/DisplayCAL-$(VERSION)-*.whl --force-reinstall;`
to:
`	pip install ./dist/DisplayCAL-0.0.0-cp312-cp312-macosx_14_0_arm64.whl --force-reinstall;`

With the file name being what I was able to locate in the 'dist' directory. Now when I run 'make install' DisplayCAL correctly installs and I run it using 'make launch' as per the documentation.

Everything works as expected once running except for 'Apply ICC Profile' after doing a calibration. As per this thread it says to copy the ICC Profiles over manually:
https://hub.displaycal.net/forums/topic/sonoma/page/3/

The ICC Profiles are located in:
/Users/username/Library/Application Support/DisplayCAL/storage/

The .icc files need to be copied to:
/Users/username/Library/ColorSync/Profiles/

They will now be accessible in macOS Display Settings and can be applied to the appropriate monitors.

M1 Ultra Mac Studio
macOS Sonoma 14.4.1

**Comment by MStraeten** [comment]
at least the manual installation description is fine with Sonoma on a M1 max. But you need to specify the whl file correctly (not …*.whl) Also the pypi installation works fine …

**Comment by eoyilmaz** [comment]
> I followed the instruction in 'How to Install' and got this error when running 'make install':

I'm guessing one of the previous commands did not finish properly

> As per this thread it says to copy the ICC Profiles over manually:

Try installing for the current use only.
