### ISSUE TITLE
IOT instruction (core dumped)

### ISSUE THREAD

**Issue by flipphillips** [eoyilmaz/displaycal-py3#362]
## Description 

After measurements, as calculations are finishing, core dumps. 

## Details / to recreate

Linux (Rocky9) 
i1Display 

Do default measure and profile.

## Expected

Success

## Actual

After measurements, as it's trying to generate the matrix it dumps core when computing the black point compensation. 

vis-

```
...
#30 Z prev 0.715490 next 0.769132 clip 
#31 Z prev 0.769132 next 0.824900 clip 
Final interpolated cLUT resolution 33x33x33
--------------------------------------------------------------------------------
Creating matrix from primaries
Using chromatic adaptation transform matrix: Bradford
Generating A2B1 by copying A2B0
Making distinct A2B0
Applying black point compensation to A2B0: L*a*b* 0.000000 0.000000 0.000000
zsh: IOT instruction (core dumped)  displaycal

```

## Regression

Could be an argyll problem, of course. Presently looking through the calls that displaycal is making / temp data.

**Comment by eoyilmaz** [comment]
Which verion of ArgyllCMS are you using?

**Comment by eoyilmaz** [comment]
Btw, I'm going to turn your message into an issue template 👍

**Comment by eoyilmaz** [comment]
closing because of inactiivty...
