### ISSUE TITLE
 This may be a dumb question but does it need to be installed at all? 

### ISSUE THREAD

**Issue by sillyspiel** [eoyilmaz/displaycal-py3#364]
Can't I just run it from the extracted folder via "python3 ./DisplayCAL.pyw" in terminal? It seems to work but I'm wondering if I'm missing anything...sorry if this is a really dumb question.

**Comment by p5k369** [comment]
Hey @sillyspiel, I'm closing this. 
The question already got asked in the duscussions and there is no issue.
See https://github.com/eoyilmaz/displaycal-py3/discussions/363
