### ISSUE TITLE
WIndows Installer

### ISSUE THREAD

**Issue by eracer001** [eoyilmaz/displaycal-py3#370]
Any way to make a windows installer available?

**Comment by eoyilmaz** [comment]
I'll look into this soon...

**Comment by mylovesaber** [comment]
Installer still unavailable. You can compile from  source code and run the program by following my toturial(3 exes to install and 10 commands from windows terminal):
https://github.com/eoyilmaz/displaycal-py3/issues/304#issuecomment-2038264396

**Comment by eracer001** [comment]
Just wanted to see if there's any work on this.  It would help so many people to have an installer.

**Comment by conceptrice26** [comment]
would also like this, Make files isn't recognized by windows or VScode even with make installed, no other solutions seem to work. Considering most of us here are likely colorists or similar and not programmers it would be nice to have an installer for windows so updates aren't a day long process.

**Comment by eoyilmaz** [comment]
Status update: I'm now able to freeze the executables... but they don't run, probably related to a missing DLL... I'm on it.

![image](https://github.com/user-attachments/assets/1f6e6727-31e8-42d1-90e7-ca268888181d)
![image](https://github.com/user-attachments/assets/39bb79a4-6a9f-486a-8e36-8a59117d32ad)

**Comment by eoyilmaz** [comment]
Found the problem, microsoft wants a 4 part version number to be listed in the manifest, so adding a "0" to the version number (3.9.12.0 instead of 3.9.12) worked :)

Now the executable starts 👍 

![displaycal_exe](https://github.com/user-attachments/assets/5b3414a4-4298-471c-bef4-d980c740bd58)

Let's work on the installer...

**Comment by eoyilmaz** [comment]
So the `DispalCAL.exe` is running... but, it is not possible to spawn a worker to run any of the ArgyllCMS executables, which is related to the `pywintypes` library configuration in the frozen ptyhon:

**Comment by eoyilmaz** [comment]
I'm wrong ImportError: `No system module 'pywintypes' (pywintypes311.dll)` is not the problem, as this will only happen if I naively run the command that the worker is running without setting the environment variables to match the frozen executables. As this works properly if I run `setattr(sys, "frozen", True)`. So the real problem I suspect is again related with the codepage being `cp1252` vs `utf-8`.

**Comment by eoyilmaz** [comment]
No :) I'm wrong, that was the problem... Fixed, and the exe is working now... Let me run a complete calibration and profiling.

**Comment by eoyilmaz** [comment]
Yeah, so it completed the profiling and installed the profile system wide without any errors. Now, let's create the installer.

**Comment by eoyilmaz** [comment]
Anyone who wants to try the installer 😎 

Please do not distribute the installer as it might contains errors and I'll create one in the releases section when we release 3.9.13

Download the [Installer](https://www.dropbox.com/scl/fi/76d1jlar6rgfxp7sm3od0/DisplayCAL-3.9.12-Setup_20240928_0037.zip?rlkey=ueh2embgdrpn5bjm8iqrkc1c8&st=e2xka7yb&dl=0
)

**Comment by eoyilmaz** [comment]
This one is working fine for me: [DisplayCAL-3.9.12-Setup_20240928_0123.zip](https://www.dropbox.com/scl/fi/msyhvafj043zdizxa5zmb/DisplayCAL-3.9.12-Setup_20240928_0123.zip?rlkey=zdc8kg9a94baeijetb594ucdr&st=m683ytsk&dl=1)

**Comment by eoyilmaz** [comment]
The executables are not signed, and I need it to be tested on any other computer than mine to see if this is creating any problems. Otherwise I need postpone releasing the installer until I learn how to sign executables under Windows.

**Comment by lostindark** [comment]
Got this when run the installer above:
<img width="370" alt="image" src="https://github.com/user-attachments/assets/3c255b93-b773-47cb-9112-3d13eb902b45">

Open profile loader -> Profile associations give me this:
<img width="339" alt="image" src="https://github.com/user-attachments/assets/f9d952f6-1367-4469-8adf-1a15743740d5">

**Comment by eoyilmaz** [comment]
@lostindark ph cool, thanks for the feedback 👍

**Comment by eoyilmaz** [comment]
@lostindark it seems that you have a non-standard VCGT that doesn't have exactly 256 entries. Can you try this: [DisplayCAL-3.9.12-Setup_20241001_1328.zip](https://www.dropbox.com/scl/fi/10voenfv9zz3uhgdvr4o6/DisplayCAL-3.9.12-Setup_20241001_1328.zip?rlkey=ckde0veylni6c02nfcrmfhc3a&st=ofth847l&dl=1)

**Comment by lostindark** [comment]
> @lostindark it seems that you have a non-standard VCGT that doesn't have exactly 256 entries. Can you try this: [DisplayCAL-3.9.12-Setup_20241001_1328.zip](https://www.dropbox.com/scl/fi/10voenfv9zz3uhgdvr4o6/DisplayCAL-3.9.12-Setup_20241001_1328.zip?rlkey=ckde0veylni6c02nfcrmfhc3a&st=ofth847l&dl=1)

This installer finishes without any errors.
I was able to open profile loader -> Profile associations, but close it gives me:
[Window Title]
DisplayCAL-apply-profiles

[Main Instruction]
WPARAM is simple, so must be an int object (got NoneType)

[Content]
TypeError: WPARAM is simple, so must be an int object (got NoneType)


[OK]

Try start calibration gives me:
<img width="368" alt="image" src="https://github.com/user-attachments/assets/b1433d14-2bb7-49ed-9455-24c2f7db4896">

**Comment by lostindark** [comment]
> Can you download [ArgyllCMS](https://www.argyllcms.com/downloadwin.html) and show the placement to DisplayCAL and try again.

ArgyIICMS is there already. Not sure why it failed to launch.

I tried to uninstall and install the old version back (3.8.9.3), works fine.

**Comment by eoyilmaz** [comment]
> WPARAM is simple, so must be an int object (got NoneType)

I can reproduce this.

Can you upload and log files with the name `DisplayCAL-apply-profiles*.log` under `%APPDATA%\DisplayCAL\logs`.

**Comment by eoyilmaz** [comment]
I'm inclained to merge this branch to #367 and release a new version all together. We now have a Windows Installer which this ticket is about, profiling and installing the profile is working. But we might have kinks that we need to fix with other tickets.

**Comment by eoyilmaz** [comment]
Okay so, this is merged to #367 and the Windows Installer will be released with 3.9.13 soon.
