### ISSUE TITLE
macos: error finding beep.wav while py2app

### ISSUE THREAD

**Issue by MStraeten** [eoyilmaz/displaycal-py3#376]
`python setup.py py2app` fails with message

```
copying file LICENSE.txt -> /Users/martinstraeten/src/displaycal-py3/dist/py2app.macosx-11.0-arm64-py3.1/DisplayCAL-3.9.12/DisplayCAL.app/Contents/Resources/./LICENSE.txt
copying file dist/net.displaycal.DisplayCAL.appdata.xml -> /Users/martinstraeten/src/displaycal-py3/dist/py2app.macosx-11.0-arm64-py3.1/DisplayCAL-3.9.12/DisplayCAL.app/Contents/Resources/metainfo/net.displaycal.DisplayCAL.appdata.xml
copying file beep.wav -> /Users/martinstraeten/src/displaycal-py3/dist/py2app.macosx-11.0-arm64-py3.1/DisplayCAL-3.9.12/DisplayCAL.app/Contents/Resources/./beep.wav
error: [Errno 2] beep.wav: 'No such file or directory'
```
where's this file expected to be copied from? it's available 
` find ./ -type f -name beep.wav` returns
```
.//dist/py2app.macosx-11.0-arm64-py3.1/DisplayCAL-3.9.12/DisplayCAL.app/Contents/Resources/lib/python3.12/DisplayCAL/beep.wav
.//DisplayCAL/beep.wav
.//.venv/lib/python3.12/site-packages/DisplayCAL/beep.wav

```
used branch: origin/develop

**Comment by eoyilmaz** [comment]
It is available under `.//DisplayCAL/beep.wav`. But... I'm not sure if `py2app` module is going to work properly. I was preparing to get concentrated on the `pyinstaller` library for building packages, it seems much reasonable as it will be possible to use a single configuration and build for Windows, Linux and MacOS.

**Comment by lukas-remis** [comment]
I have never, ever found a software realeased as source to be compilling properly.
Please release some installer or .deb/AppImage package. Thank you!

**Comment by MStraeten** [comment]
> It is available under `.//DisplayCAL/beep.wav`. But... I'm not sure if `py2app` module is going to work properly. I was preparing to get concentrated on the `pyinstaller` library for building packages, it seems much reasonable as it will be possible to use a single configuration and build for Windows, Linux and MacOS.

it seems beep.wav and further stuff from ./DisplayCal is expected to be in ./

**Comment by eoyilmaz** [comment]
Should be fixed with 900152f

**Comment by eoyilmaz** [comment]
Our `setup.py` is unnecessarily complicated, trying to juggle a lot of files under a lot of different OS and config combinations, I'm planning to refactor it as I started to remove some of the combinations to their own modules.

**Comment by MStraeten** [comment]
doesn't work with macos
steps:
`cd displaycal-py3`
`make build `--> fine
`make install` --> fine
`python setup.py py2app` can't find beep.wav

**Comment by eoyilmaz** [comment]
@MStraeten you need to checkout to the correct branch:

```shell
cd displaycal-py3
git fetch --all
git checkout 348-beepwav-and-others-not-properly-transferred-with-package_data
git pull
make venv build install
python setup.py py2app
```

I can generate a proper macos apple silicon app.

**Comment by eoyilmaz** [comment]
oh yeah I'm handling this as a part of #348 btw
