### ISSUE TITLE
A word to the developers

### ISSUE THREAD

**Issue by JavaGaoshou** [eoyilmaz/displaycal-py3#386]
I have the following expectations:
1. When using various CMFs, the corresponding white point coordinates are converted instead of CIE1931, and the length of the coordinates should be longer than 4 decimal places. (If anyone knows the corresponding coordinates of various CMFs in DisplayCal, they can reply here.)
2. Added the ability to add MHC2 tags to ICC files, which is a new generation of color management for Windows.
3. When using the interactive display adjustment and adjusting the measurement area to full screen, the interactive window is below the test window and cannot be clicked, which needs to be improved here.
4. Launched the Windows version of the installation package and self-extracting program.
5. Directly convert ICC to 3dlut without using any source color space.
6. Add cie2015 Observer.
Displayedcal is excellent, and you are even more so, thank you for your efforts.

**Comment by MStraeten** [comment]
don’t forget that argyllcms is working under the hood. So you need to ask for some of your requests there (http://www.argyllcms.com/
