### ISSUE TITLE
opensuse tumbleweed setup.py syntax error

### ISSUE THREAD

**Issue by reindeerphotode** [eoyilmaz/displaycal-py3#39]
Dear Erkan,

I never raised an issue on github or anywhere else. But I use Opensuse tumbleweed and would like to use DisplayCal. Therefore your attempt to move DisplayCal from python 2.7 to python 3.X is highly appreciated.

After  git clone I got:

marc@localhost:~/python/displaycal-py3> python setup.py install
  File "setup.py", line 34
    srcdir = f"py2app.{get_platform()}-py{sys.version[:3]}"
                                                          ^
SyntaxError: invalid syntax
marc@localhost:~/python/displaycal-py3> 

may be this is interesting for you...

Best regards

   Marc

**Comment by p5k369** [comment]
Hi Marc,
are you sure "python" is linked to the right interpreter?
try:
python3 setup.py install

**Comment by reindeerphotode** [comment]
Hi p5k369,

thank you so much!
Meanwhile I realized exactly that.
Right now I am setting up gcc (do not laugh:-))

"python" was not linked with anything at all (Standard Opensuse Tumbleweed)

python3 setup.py install
did the job.
Now I am collecting the missing includes...
Maybe I'll end up with really some help to the project...

Have a lot of fun
