### ISSUE TITLE
Sonoma 14.4 & Spyder X black screen

### ISSUE THREAD

**Issue by Tonym69** [eoyilmaz/displaycal-py3#395]
Hello,
I'm trying to calibrate the Iiyama ProLite XB3070WQS monitor attached to my MacBook Air M1.

About 8 minutes into calibration, there is a "whooshing wind" sound effect (maybe completion of calibration?) and both monitors go black (not disabled, just black pixel values).

From there, system is visually unresponsive. If I blindly tab through open apps then some produce keyboard error tones and some do not, so it seem the system is still running in the background but nothing works to restore the displays.

Only way out is to force shutdown.

Is there a place where I would find an error log or record after reboot? I can offer no further info about the problem, only what I described.

Running MacOS Sonoma 14.4 on 2020 MacBook Air M1 using a DataColor SpyderX.
Python 3.12.5
also wxPython 4.2.1 (both read from launch commentary in Terminal)
DisplayCal 3.9.12
Argyll "up to date" according to launch commentary (downloaded this morning, don't know version)

Any help appreciated! Thanks.

**Comment by son01490517** [comment]
This bug has been present since the original DisplayCal (Python 2.x). Just unplug the monitor and plug it back in and it will work fine. I am using a dummy HDMI via type C hub, just plug it in and out with the same result.

**Comment by Tonym69** [comment]
That's very helpful, thank you! I will have another go and see what happens.
Tony

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by eoyilmaz** [comment]
I believe there is an issue related to ArgyllCMS's `dispwin` command, running `dispwin -d1 -L` over a couple of times randomly sets the display to black. It still happens with ArgyllCMS V3.3.0.

**Comment by eoyilmaz** [comment]
Closing this as this is ArgyllCMS related issue and not DisplayCAL.
