### ISSUE TITLE
New release please ?

### ISSUE THREAD

**Issue by marillat** [eoyilmaz/displaycal-py3#401]
As 3.12 is the default python in most distribution,
so It is possible to have a new release ?

**Comment by eoyilmaz** [comment]
I'm waiting for #367 and #370 then will release 3.9.13

**Comment by eoyilmaz** [comment]
3.9.13 is now released 👍

**Comment by marillat** [comment]
Thanks. Package uploaded in unstable.

**Comment by eoyilmaz** [comment]
3.9.14 is now released
