### ISSUE TITLE
Fail to open Calibrate window

### ISSUE THREAD

**Issue by marillat** [eoyilmaz/displaycal-py3#415]
With displaycal 3.9.13 called with --debug

```shell
Reloading /home/marillat/.config/dispcalGUI/dispcalGUI.ini
[D] get_set_display
[D] display_ctrl_handler called for ID -2023 display_ctrl event type 10013 EVT_CHOICE
┌──────────────────────────────────────────────────────────────────────────────┐
│ b'Traceback (most recent call last):\n  File "<string>", line 1, in          │
│ <module>\nModuleNotFoundError: No module named \'wxMeasureFrame\''           │
└──────────────────────────────────────────────────────────────────────────────┘
[D] focus_handler called for None <class 'wx._core.Menu'>, event type 10017 EVT_TOOL_RANGE
[D] Last focused control: ID -2423 calibrate_and_profile_btn <class 'DisplayCAL.wxwindows.BorderGradientButton'>
Executing BaseApp.OnExit()
```

**Comment by eoyilmaz** [comment]
Please use the bug report format and supply steps to reproduce.

**Comment by marillat** [comment]
Launch displaycal
Click on the `Calibrate &profile` buton
displaycal crash

**Comment by eoyilmaz** [comment]
You should start from how did you install DisplayCAL.

**Comment by eoyilmaz** [comment]
It really depends on how you have installed. Let me check now if I can reproduce this.

**Comment by marillat** [comment]
displaycal has been always working with files installed like this

https://packages.debian.org/sid/amd64/displaycal/filelist

**Comment by eoyilmaz** [comment]
Yes, but sometimes, unfortunately, we introduce bugs, and knowing the way you installed helps to pinpoint the bug.

**Comment by marillat** [comment]
Yes, I do the same (sometimes) with the Debian packaging.

**Comment by eoyilmaz** [comment]
> ```shell
> ┌──────────────────────────────────────────────────────────────────────────────┐
> │ b'Traceback (most recent call last):\n  File "<string>", line 1, in          │
> │ <module>\nModuleNotFoundError: No module named \'wxMeasureFrame\''           │
> └──────────────────────────────────────────────────────────────────────────────┘
> ```

I know why this is happening. 6c00bfb changed the `pydir` and `DisplayCAL.display_cal.MainFrame.start_measurement_subprocess()` is referencing that path, which now shows the parent of the previous value. Should be easy to fix.

**Comment by eoyilmaz** [comment]
ah no, my mistake, the pydir is still pointing to the same folder. But that script should import `DisplayCAL.wxMeasureFrame` and not `wxMeasureFrame` directly.

**Comment by eoyilmaz** [comment]
I'm using a virtualbox image for Debian 12, but I can't seem to be able to build and install wxPython. I'll try with Ubuntu 24.10 which was building okay. I should hit to the same error, if I'm able to start the calibration with the virtual monitor at all.

**Comment by eoyilmaz** [comment]
hmm... ArgyllCMS executables are not working under aarch64 🤷‍♂️ 

let me do it remotely then, I'll update the code, and I'll be appriciated if you can try running it.

**Comment by marillat** [comment]
As I'm saying before, I'm the Debian maintainer and we don't use python virtual environment to build the package but pybuild.

Commit https://github.com/eoyilmaz/displaycal-py3/commit/90b7192300f991ff7d6cbdac7c7ba5c1094ae38d fix this issue.

**Comment by eoyilmaz** [comment]
> As I'm saying before, I'm the Debian maintainer and we don't use python virtual environment to build the package but pybuild.

oh sorry, my bad, didn't understood you are the Debian maintainer, cool!

I'm glad that the problem is solved. I'll do a new release this week, I'll let you know 👍

**Comment by marillat** [comment]
I've already uploaded a new package 3.9.13-4 not yet available in unstable.

Thanks for your work and fast bug fixes.

**Comment by eoyilmaz** [comment]
3.9.14 is released
