### ISSUE TITLE
What would be needed to maintain this and add it to the Archlinux User Repository AUR ?

### ISSUE THREAD

**Issue by zDEFz** [eoyilmaz/displaycal-py3#449]
As described.

**Comment by eoyilmaz** [comment]
I think there are people already maintaining DisplayCAL in ArchLinux, you should contact them if you have any problems specific to DisplayCAL package for ArchLinux: https://archlinux.org/packages/extra/x86_64/displaycal/

**Comment by zDEFz** [comment]
> I think there are people already maintaining DisplayCAL in ArchLinux, you should contact them if you have any problems specific to DisplayCAL package for ArchLinux: https://archlinux.org/packages/extra/x86_64/displaycal/

That's off-topic.
This version is a fork and forks are always going into the AUR before they get into upstream.

**Comment by eoyilmaz** [comment]
This is not a fork... it kind of is... but this is DisplayCAL itself, just maintained by somebody else, as the original developer stopped working on it 3-4 years ago...

**Comment by jarrard** [comment]
> I think there are people already maintaining DisplayCAL in ArchLinux,

It's been broken for over a month under Arch now due to some python update the broke it?  Anyway, nobody is maintaining it atm.
