### ISSUE TITLE
Add dependency requirements to install instructions for easier install/development

### ISSUE THREAD

**Issue by meyerkev** [eoyilmaz/displaycal-py3#48]
I also want to make both a Makefile and Dockerfile, but I spent about half an hour on a brand new M1 Mac and your missing dependencies are 

If I can have permission to push a PR, I have a first draft of the commit ready to go.

**Comment by eoyilmaz** [comment]
I dropped a note on your PR, there is a ``requirements.txt`` file which you can use with ``pip``:

```shell
pip install -r requirements.txt
```

and on top of that for development:

```shell
pip install -r requirements-dev.txt
```

can be used.

There is no need to have a permission to push a PR and you already did that, I think you've written that before creating the PR.

**Comment by meyerkev** [comment]
Unfortunately, unless you install the packages first, the requirements.txt doesn't install correctly.  So you need to install the packages so the Python libraries have C libraries to hook into.  

This is the list I came up with off trying to setup the docker image, though dbus in Docker is interesting and I think I'm going to give it a second go and https://github.com/meyerkev/displaycal-1/tree/docker_image should be considered non-working at this time.

**Comment by eoyilmaz** [comment]
Okay got it, can you check the following file for the Debian requirements, it might help:

https://github.com/eoyilmaz/displaycal-py3/blob/python3/.github/workflows/pytest.yml

**Comment by meyerkev** [comment]
Taking a look now, but I'll also close this issue.
