### ISSUE TITLE
``struct.errror`` in ``DictType.tagData``

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#50]
Dear Erkan,

I did a full rebuild and removed  `$HOME/.config/DisplayCAL` completely.

Result: Another CAST Problem: string to byte or vice versa.

DisplayCAL did an output on a window:
![Screenshot_20220320_104055_DisplayCAL](https://user-images.githubusercontent.com/101870638/159156715-1ec72a43-a753-4863-8516-537e73103da1.png)

Error output on the terminal:
`TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
--------------------------------------------------------------------------------
/usr/lib64/python3.8/site-packages/DisplayCAL/colord.py:182: Warning: CDError("gi.repository.GLib.Error: GLib.Error('GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ColorManager was not provided by any .service files', 'g-dbus-error-quark', 2)")
  warnings.warn(safe_str(exception), Warning)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/wx/lib/delayedresult.py", line 267, in wrapper
    result = workerFn(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 1838, in __call__
    result = self.producer(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 11572, in create_profile
    result = self.update_profile(
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 12329, in update_profile
    profile.calculateID()
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 6645, in calculateID
    data = self.data
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 8041, in __getattribute__
    return object.__getattribute__(self, name)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 6445, in data
    tagData = self.tags[tagSignature].tagData
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 4653, in tagData
    tagData.append(uInt32Number_tohex(size))
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 2871, in uInt32Number_tohex
    return struct.pack(">I", int(round(num)))
struct.error: 'I' format requires 0 <= number <= 4294967295

DisplayCAL: Uninhibited org.freedesktop.ScreenSaver
DisplayCAL: Uninhibited org.freedesktop.PowerManagement.Inhibit
`
Best regards

   Marc

_Originally posted by @reindeerphotode in https://github.com/eoyilmaz/displaycal-py3/issues/40#issuecomment-1073212489_

**Comment by eoyilmaz** [comment]
@reindeerphotode I can't reproduce this error. Can you send over the generated ICC profile under ``$HOME/.local/share/DisplayCAL/storage/{ICC_Profile_Name}/{ICC_Profile_Name}.icc``

**Comment by reindeerphotode** [comment]
Dear Erkan,

the corresponding ICC profile:
Complete stuff in the directory:
ET430K #1 2022-03-20 09-36 2.2 F-S XYZLUT+MTX
(Due to upload complains by github renamed to *.txt)

[0_16.log](https://github.com/eoyilmaz/displaycal-py3/files/8313328/0_16.log)
[0_16.log.txt](https://github.com/eoyilmaz/displaycal-py3/files/8313332/0_16.log.txt)
[0_16.ti1.txt](https://github.com/eoyilmaz/displaycal-py3/files/8313333/0_16.ti1.txt)
[0_16.ti3.txt](https://github.com/eoyilmaz/displaycal-py3/files/8313334/0_16.ti3.txt)
[ET430K #1 2022-03-20 09-36 2.2 F-S XYZLUT+MTX.cal.txt](https://github.com/eoyilmaz/displaycal-py3/files/8313335/ET430K.1.2022-03-20.09-36.2.2.F-S.XYZLUT%2BMTX.cal.txt)
[ET430K #1 2022-03-20 09-36 2.2 F-S XYZLUT+MTX.log.txt](https://github.com/eoyilmaz/displaycal-py3/files/8313336/ET430K.1.2022-03-20.09-36.2.2.F-S.XYZLUT%2BMTX.log.txt)
[ET430K #1 2022-03-20 09-36 2.2 F-S XYZLUT+MTX.ti1.txt](https://github.com/eoyilmaz/displaycal-py3/files/8313337/ET430K.1.2022-03-20.09-36.2.2.F-S.XYZLUT%2BMTX.ti1.txt)
[ET430K #1 2022-03-20 09-36 2.2 F-S XYZLUT+MTX.ti3.txt](https://github.com/eoyilmaz/displaycal-py3/files/8313338/ET430K.1.2022-03-20.09-36.2.2.F-S.XYZLUT%2BMTX.ti3.txt)

I hope this helps

best regards

   Marc

**Comment by reindeerphotode** [comment]
Dear Erkan (@eoyilmaz),

i did a clean restart today morning. I got the very same messages including the error message by DisplayCal istself.

best regards

   Marc

**Comment by eoyilmaz** [comment]
Hey @reindeerphotode thank you, I'll look into this today.

**Comment by eoyilmaz** [comment]
@reindeerphotode I looked in to the files you sent, because DisplayCAL errors out before creating the ICCProfile I can't reproduce the error. But I've updated the code so it will at least print out the erroneous value before the error. Can you please try profiling it again.

Also, looking at the files I see that your white point is set over 13000 K (hence ``Target white value is XYZ 185.050077 191.535886 321.011139 [xy 0.265268 0.274565]``)which is super blue, I think you are not setting a target white point value and I recommend setting it to 6500 K

**Comment by reindeerphotode** [comment]
Dier Erkan (@eoyilmaz)

thank you for your reply. I was not aware of the fact I set the color temperature to 13000K... (Please point me to "How do I calculate the 13000K out of these white value XYZ 185.050077 191.535886 321.011139")

The calibration is running first without changing the color temperature (How do I do this anyway?)

btw. Is there a way to tell setup.py checking for python modules and if missing to install them?
send2trash is newly needed and was missing in my python. 

(Please forgive me but my programming experience is connected to FORTRAN77, C and if needed with pearl, but never from scratch... more like using what was needed without really learning a language... (and this is 20years ago))

**Comment by reindeerphotode** [comment]
Dear Erkan (@eoyilmaz )

here is the output:

![Screenshot_20220322_081704_DisplayCal](https://user-images.githubusercontent.com/101870638/159427794-c3228082-5736-4c00-8fac-2180070b46bb.png)

Intersecting volume = 754597.2 cubic units
'/usr/local/share/DisplayCAL/ref/SMPTE431_P3.gam' volume = 1176953.5 cubic units, intersect = 64.11%
'ET430K #1 2022-03-22 07-28 2.2 F-S XYZLUT+MTX.gam' volume = 754815.9 cubic units, intersect = 99.97%

TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')

(here I skip the "-----" )

/usr/lib64/python3.8/site-packages/DisplayCAL/colord.py:182: Warning: CDError("gi.repository.GLib.Error: GLib.Error('GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ColorManager was not provided by any .service files', 'g-dbus-error-quark', 2)")
  warnings.warn(safe_str(exception), Warning)
num: 15351378462
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/wx/lib/delayedresult.py", line 267, in wrapper
    result = workerFn(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 1839, in __call__
    result = self.producer(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 11573, in create_profile
    result = self.update_profile(
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 12330, in update_profile
    profile.calculateID()
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 6649, in calculateID
    data = self.data
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 8044, in __getattribute__
    return object.__getattribute__(self, name)
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 6449, in data
    tagData = self.tags[tagSignature].tagData
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 4657, in tagData
    tagData.append(uInt32Number_tohex(size))
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 2875, in uInt32Number_tohex
    raise e
  File "/usr/lib64/python3.8/site-packages/DisplayCAL/ICCProfile.py", line 2872, in uInt32Number_tohex
    return struct.pack(">I", int(round(num)))
struct.error: 'I' format requires 0 <= number <= 4294967295

DisplayCAL: Uninhibited org.freedesktop.ScreenSaver
DisplayCAL: Uninhibited org.freedesktop.PowerManagement.Inhibit

after stopping dislpaycal:

Executing BaseApp.OnExit()
Running application exit handlers
lockfilename: /home/marc/.config/DisplayCAL/DisplayCAL.lock
oport: 43739
fn: <built-in function flock>
args: (6, 2)


Best regards

   Marc

**Comment by eoyilmaz** [comment]
> num: 15351378462

Okay this is the problem, this number is too big for the ``uInt32Number_tohex`` to pack. Let see who is generating this huge number.

> I was not aware of the fact I set the colour temperature to 13000K... 

No no, sorry if I misguided you, you are not setting the colour temperature too high, it is the ``Color Target`` setting, you probably left it in ``As Measured`` and your monitor white level is too off. I suggest selecting ``Color Temperature`` from that setting and selecting ``6500 K`` and then adjust the white level with the options on the monitor itself. I slightly digress from the main topic here but please ensure ``Blue Light`` setting is turned off:

![image](https://user-images.githubusercontent.com/1786804/159438927-2c44b5ae-6714-4f38-9724-1e09648500ba.png)

And from the ``Color`` menu set the ``Gamma`` to ``2.2`` and ``Color Temp`` to ``User`` and while in the ``Interactive display adjustment (Visual White Point)`` edtior in DisplayCAL adjust the ``R Gain``, ``G Gain`` and ``B Gain`` values accordingly so that the white point matches 6500 K from the hardware:

![image](https://user-images.githubusercontent.com/1786804/159439395-416bc6ae-74e9-446d-9fbd-1d579d7f5826.png)

I don't recommend touching the ``R Bias``, ``G Bias`` or ``B Bias`` values.

![image](https://user-images.githubusercontent.com/1786804/159440065-7ff3b141-4212-4d19-90fc-bba45361ae89.png)

As you see, mine is slightly off, because my monitor has a factory calibrated ``Uniformity Compensation`` and get disabled when I touch ``RGB Gain`` values I leave it like that.

I guess yours should have a prominent blue bar.

And another warning, after you adjust your white balance (this is the ``calibration`` part of the ``profiling`` by the way) you would feel that everything started become yellow, but it is completely perceptual after seeing that much blue a normal grey value will look like yellow to you, this affect will warn out after couple of hours of usage, don't worry.

Oh your luminance levels are too high too. But this is very dependent on your personal preference and the brightness of your environment that you are looking to that monitor. So, I'm not saying anything on that.

I'll update the code and let you know, when you can do another test, thank you very much for your efforts by the way :+1:

**Comment by eoyilmaz** [comment]
One another thing that will help me hugely is to run the following command on the terminal:

```shell
xrandr --verbose > xrandr_output.txt
```

and please upload the ``xrandr_output.txt`` here.

**Comment by eoyilmaz** [comment]
Okay @reindeerphotode can you please try and paste the output here again, thanks!

**Comment by reindeerphotode** [comment]
Dear Erkan,

xrandr --verbose gives:
[xrandr_output.txt](https://github.com/eoyilmaz/displaycal-py3/files/8325972/xrandr_output.txt)

Best regards

   Marc

Ps. Test runs right now and thank you for the off topic discussion!!!!!!

**Comment by reindeerphotode** [comment]
After 1.5h or so. DisplayCal said it finished. But the data collection(?) took for ever. The xterm in which I started displaycal printed zeros forever.

Testrun:
displaycal &>> displaycal_20220322.txt
in order to get everything:-)

**Comment by eoyilmaz** [comment]
Okay thanks for the ``xrandr`` output, let's see if it is going to reveal the error

**Comment by reindeerphotode** [comment]
The output file hat 7.1 GiB...
I try to send the first 10MB
[xaa.txt](https://github.com/eoyilmaz/displaycal-py3/files/8327935/xaa.txt)

**Comment by reindeerphotode** [comment]
I can test it using an ubuntu installation in a virtual machine, if necessary:-)

**Comment by eoyilmaz** [comment]
> The output file had 7.1 GiB... I try to send the first 10MB [xaa.txt](https://github.com/eoyilmaz/displaycal-py3/files/8327935/xaa.txt)

Great, this will help :+1:  it seems that the ``EDID_serial`` is not calculated correctly.

**Comment by eoyilmaz** [comment]
Okay I found the problem and reproduced it :+1:

**Comment by eoyilmaz** [comment]
@reindeerphotode  Can you try it now :crossed_fingers:

**Comment by reindeerphotode** [comment]
... now. sorry for the delay!

**Comment by reindeerphotode** [comment]
Thank you very much!

It runs through and I got a calibration!

I would like to help further:-)

**Comment by eoyilmaz** [comment]
Hey, yeah, that's very nice to hear!
Yeah, sure, please test as much as you can, and report any hiccups you encounter :+1:
