### ISSUE TITLE
Add standard development commands to the Makefile

### ISSUE THREAD

**Issue by meyerkev** [eoyilmaz/displaycal-py3#51]
In particular, can we update the Makefile and README: 

1. How do we auto-lint?
2. How do we run tests?  And against which folders?
3. What commands do we run to install the dependencies 

At a guess #3 is just a `pip install -r requirements.txt && pip install -r requirements-dev.txt`, but requirements-dev.txt is giving me fits because it takes 20 minutes just to fail to install after I tried to make it multi-core when it took nearly an hour between crashes in single-core.

**Comment by meyerkev** [comment]
This is not complete in large part because this is a discoverability problem, but I added a `make requirements` to our dependencies. 

https://github.com/eoyilmaz/displaycal-py3/pull/52

**Comment by meyerkev** [comment]
`make test` is, in a non-python-version and non-architecture-dependent way: 

```
cp build/lib.linux-x86_64-3.8/DisplayCAL/lib64/python38//RealDisplaySizeMM.cpython-38-x86_64-linux-gnu.so DisplayCAL/lib64/python38/
LD_LIBRARY_PATH=build/lib.linux-x86_64-3.8/DisplayCAL/lib64/python38/ PYTHONPATH=${PYTHONPATH}:build/lib.linux-x86_64-3.8/:build/lib.linux-x86_64-3.8/DisplayCAL/lib64/python38/ python -m pytest tests
```

**Comment by eoyilmaz** [comment]
Hey @meyerkev would you like to look in to the new install instructions in the ``README.md`` file. I've included instructions for creating a ``virtualenv`` and installing it through the regular commands, You may want to add a section that does that with the ``make`` command.

**Comment by eoyilmaz** [comment]
Otherwise I believe we can close this ticket, what do you think?

**Comment by meyerkev** [comment]
I would still love to have a standard "make test" and "make lint" command for local work.

**Comment by eoyilmaz** [comment]
kind of done already (no make lint, but coming)... closing...
