### ISSUE TITLE
[Code] Architecture

### ISSUE THREAD

**Issue by Doomsdayrs** [eoyilmaz/displaycal-py3#54]
What is the current architecture of this application?

**Comment by Doomsdayrs** [comment]
if any..

**Comment by eoyilmaz** [comment]
By architecture you mean the target OS?

**Comment by Doomsdayrs** [comment]
> By architecture you mean the target OS?

Architecture as in how the code has been built.

Similar to buildings, when coding an application one must have an architecture design in mind to make coding clean and consistent.

With my work with developing Android applications, I know first hand the importance of proper code structure and design.

**Comment by eoyilmaz** [comment]
I think you need to ask this to Florian. I'm not designing a new application here.
