### ISSUE TITLE
[Community] Matrix

### ISSUE THREAD

**Issue by Doomsdayrs** [eoyilmaz/displaycal-py3#55]
I created a Matrix room for discussion.

Many teams use Matrix nowadays for community interaction and discussion. Such examples like Flatpak, GNOME, KDE, GTK, WayDroid, FSF, Etc.

https://matrix.to/#/#displaycal-py3:matrix.org

**Comment by eoyilmaz** [comment]
Hey thanks for that. Would you like to update the README file with that.

**Comment by Doomsdayrs** [comment]
Sure, One moment

**Comment by Doomsdayrs** [comment]
@eoyilmaz You should come join too
