### ISSUE TITLE
[Branding] Icon

### ISSUE THREAD

**Issue by Doomsdayrs** [eoyilmaz/displaycal-py3#56]
Currently we are using the icons of old, and there is *many* different variants of icons and other images at different sizes. For sake of scope, we will discuss the icon only.

I think it would be best to create a new SVG logo, which can work on any resolution and scale. And is easily editable for tweaks and such forth.

**Comment by eoyilmaz** [comment]
I can do that :+1: 

Did you see this #45 :smile:

**Comment by Doomsdayrs** [comment]
> I can do that +1

You don't have to do it yourself right away, it is not a major priority but something to keep in mind.

> Did you see this #45 smile

I just did, looks excellent!

**Comment by eoyilmaz** [comment]
> You don't have to do it yourself right away, it is not a major priority but something to keep in mind.

"I can do that" was not a reference to when to do it, I just volunteered for the work...
