### ISSUE TITLE
Install profile as system default ---> does not work

### ISSUE THREAD

**Issue by reindeerphotode** [eoyilmaz/displaycal-py3#76]
Dear Erkan,

again me...
After a full calibration run I checked the calibration (show profile calibration).
I wanted to set it as system default. These are the error messages I got:

About to open dispwin object on the display
About to clear the calibration
About to set display to given calibration
Calibration set
About to destroy dispwin object
...ok.
/usr/lib64/python3.8/site-packages/DisplayCAL/colormath.py:1277: Warning: Daylight CCT is only accurate down to about 4000 K
  warnings.warn("Daylight CCT is only accurate down to about 4000 K", Warning)
Authentification

```shell
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/display_cal.py", line  │
│ 11477, in <lambda>                                                           │
│     wx.EVT_BUTTON, lambda event: self.profile_finish_action(event.Id)        │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/display_cal.py", line  │
│ 11573, in profile_finish_action                                              │
│     result = self.worker.authenticate(                                       │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 2571, │
│ in authenticate                                                              │
│     result, pwd = self.sudo.authenticate(args, title, parent)                │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 2039, │
│ in authenticate                                                              │
│     return self.is_allowed(args, pwd), pwd                                   │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 2069, │
│ in is_allowed                                                                │
│     self._terminate()                                                        │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 1939, │
│ in _terminate                                                                │
│     print(self.subprocess.before.strip().decode(enc, "replace"))             │
│ AttributeError: 'str' object has no attribute 'decode'                       │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by reindeerphotode** [comment]
The same happens by clicking the install profile button:

![Screenshot_20220402_122916_Displaycal_mark](https://user-images.githubusercontent.com/101870638/161379166-3d4a3910-c86c-4489-9043-c9f836680b56.png)

**Comment by eoyilmaz** [comment]
Cool cool, will fix it today :+1:

**Comment by eoyilmaz** [comment]
Can you try it again.

**Comment by reindeerphotode** [comment]
Just clicking the install profile button results in the following error:
(I'll redo it without miss typing my root password;-))

note the str object. (string object?)

![Screenshot_20220402_163155_Displaycal](https://user-images.githubusercontent.com/101870638/161388032-090873cf-15d8-4262-bc09-953b712e0d6b.png)


Authentification
sudo: 1 incorrect password attempt
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/display_cal.py", line  │
│ 11495, in <lambda>                                                           │
│     wx.EVT_BUTTON, lambda event: self.profile_finish_action(event.Id)        │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/display_cal.py", line  │
│ 11591, in profile_finish_action                                              │
│     result = self.worker.authenticate(                                       │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 2574, │
│ in authenticate                                                              │
│     result, pwd = self.sudo.authenticate(args, title, parent)                │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 2042, │
│ in authenticate                                                              │
│     return self.is_allowed(args, pwd), pwd                                   │
│   File "/usr/lib64/python3.8/site-packages/DisplayCAL/worker.py", line 2074, │
│ in is_allowed                                                                │
│     p.before.strip().decode(enc, "replace"), 0                               │
│ AttributeError: 'str' object has no attribute 'decode'                       │
└──────────────────────────────────────────────────────────────────────────────┘

**Comment by reindeerphotode** [comment]
please find the the error messages in this txt-file. (in the third line **lambda** is missing in the copy and paste version above...
[DisplayCal_20220402.txt](https://github.com/eoyilmaz/displaycal-py3/files/8402729/DisplayCal_20220402.txt)

**Comment by eoyilmaz** [comment]
Can you please try it again :+1:

**Comment by reindeerphotode** [comment]
Just a status message from me...

No error messages anymore but:
It works with sudo. By default in SuSE Systems no one is in /etc/sudoers. So by using the root password a sudo works.
My root password is not accepted (and yes normally the problem sits in between the keyboard and the chair-back. Even copying the previous typed password does not work...)
typing 
sudo  ´some command´
works fine...

**Comment by reindeerphotode** [comment]
sudo -l

User marc may run the following commands on localhost:
    (ALL) ALL
    (ALL : ALL) ALL

so i am allowed to do this...

But still:
...ok.
Authentification
Sorry, try again.

**Comment by reindeerphotode** [comment]
btw: running displaycal as root works of course:-)

**Comment by eoyilmaz** [comment]
I can not reproduce this error. But my user is in ``sudoers``, maybe that's the problem as you said in SuSE no one is in ``sudoers``. As a workaround just install the profile for your user for now.

**Comment by eoyilmaz** [comment]
#93 is closed, and we didn't have any new messages on this issue. So closing it for now. If you still have this issue, please open it again :+1:
