### ISSUE TITLE
Debug: window wxSpinCtrlDouble lost focus even though it didn't have it

### ISSUE THREAD

**Issue by reindeerphotode** [eoyilmaz/displaycal-py3#77]
Just starting displaycal gives:

Check for application update...
DisplayCAL is up-to-date.
ArgyllCMS is up-to-date.
12:17:30: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:17:30: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:17:30: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:17:30: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:17:30: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:17:30: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:25:05: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:25:05: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:25:05: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:25:05: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:25:05: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
12:25:05: Debug: window wxSpinCtrlDouble(0x55a748043000) lost focus even though it didn't have it
Loading calibration curves from file...

**Comment by eoyilmaz** [comment]
This is not very important and in fact this is not a bug. I believe, these kind of warnings will be solved when we switch to Qt.
