### ISSUE TITLE
Names in ICC Profiles

### ISSUE THREAD

**Issue by reindeerphotode** [eoyilmaz/displaycal-py3#82]
I have now idea where the names of the ICC Profiles are generated but there shouldn't be spaces or strange characters like ^2 and so on. I am a bit old fashioned I know but to cop with ASCII <-> Unicode stuff is no fun;-)

**Comment by eoyilmaz** [comment]
I'm not keen on spaces too. But, you should be able to adjust the name of the resultant ICC profile (and anything related to the generated files) on the ``Profiling`` tab using ``Profile Name`` section.

**Comment by eoyilmaz** [comment]
![image](https://user-images.githubusercontent.com/1786804/161519258-cedb071d-42ed-4bce-8222-4e59a84af13d.png)

**Comment by reindeerphotode** [comment]
thank you!!!!!!!
