### ISSUE TITLE
interactive display adjustment issue

### ISSUE THREAD

**Issue by ctouz** [eoyilmaz/displaycal-py3#85]
I wanted to test displaycal-py3, at the beginning of the calibration an error occurs with the interactive display adjustment.:
DisplayCAL: Waiting for send buffer
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/lib/agw/pygauge.py",    │
│ line 264, in OnPaint                                                         │
│     r.width = w                                                              │
│ TypeError: 'float' object cannot be interpreted as an integer

**Comment by eoyilmaz** [comment]
Should be fixed now

**Comment by ctouz** [comment]
Yes,solved.
