### ISSUE TITLE
messages during calibration

### ISSUE THREAD

**Issue by ctouz** [eoyilmaz/displaycal-py3#87]
the calibration continues until the end with 2 times this message.
Commencing display calibration

┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib/python3.10/site-packages/wx/core.py", line 2326, in Notify  │
│     self.notify()                                                            │
│   File "/usr/lib/python3.10/site-packages/wx/core.py", line 3532, in Notify  │
│     self.result = self.callable(*self.args, **self.kwargs)                   │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxwindows.py", line     │
│ 6479, in <lambda>                                                            │
│     wx.CallLater(50, lambda: self and self.IsShown() and                     │
│ self.animbmp.Play(24))                                                       │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxwindows.py", line     │
│ 334, in Play                                                                 │
│     self._timer.Start(1000.0 / fps)                                          │
│ TypeError: Timer.Start(): argument 1 has unexpected type 'float'             │
└────────────────────────────────────────────────────

**Comment by eoyilmaz** [comment]
Should be fixe now

**Comment by eoyilmaz** [comment]
By the way because you are using Python 3.10 and implicit cast is now deprecated with it you will get these kind of errors. But please report them as you get them. Thank you for your efforts.
