### ISSUE TITLE
LUTViewer cannot draw anything with Python 3.10

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#89]
Under Python 3.10 the LUTViewer can not draw anything (ICC profiles, gamut curves etc.). I can't seem to find the cause. But let's have this reported here.

**Comment by ctouz** [comment]
Launching Synthetic ICC:
Traceback (most recent call last):                                           │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 549, in  │
│ main                                                                         │
│     _main(module, name, applockfilename)                                     │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 536, in  │
│ _main                                                                        │
│     main()                                                                   │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1347, in main                                                           │
│     app.TopWindow = SynthICCFrame()                                          │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 146, in __init__                                                        │
│     self.update_controls()                                                   │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1219, in update_controls                                                │
│     self.update_trc_controls()                                               │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1300, in update_trc_controls                                            │
│     self.profile_class_ctrl.GetStringSelection() ==                          │
│ self.profile_classes["scnr"]                                                 │
│ KeyError: 'scnr'                                                             │
└──────────────────────────────────────────────────────────────────────────────┘
OS:Manjaro linux

**Comment by ctouz** [comment]
displaycal-profile-info
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7f12401132e0>
displaycal-profile-info 3.9.0 2022-04-09T08:02:57Z
manjaro 21.2.5 Qonos x86_64
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Faulthandler 
wxPython 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /home/christian/.config/DisplayCAL/DisplayCAL.ini
listening
writing to lock file: port: 15411
Configuration de l’hôte de scripting à 127.0.0.1:15411
/usr/lib/python3.10/site-packages/DisplayCAL/colord.py:182: Warning: CDError("gi.repository.GLib.Error: GLib.Error('GDBus.Error:org.freedesktop.ColorManager.NotFound: property match 'OutputEdidMd5'='758c415991ac72a631cbd10bd0507c37' does not exist', 'g-io-error-quark', 36)")
  warnings.warn(safe_str(exception), Warning)

**Comment by ctouz** [comment]
Sille an issue:
displaycal-synthprofile
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7ff1bf47f2b0>
displaycal-synthprofile 3.9.2 2022-04-30T16:13:37Z
manjaro 21.2.6 Qonos x86_64
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
Faulthandler 
wxPython 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /home/christian/.config/DisplayCAL/DisplayCAL.ini
Existing client using port 15411
listening
writing to lock file: port: 43455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 549, in main
    _main(module, name, applockfilename)
  File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 536, in _main
    main()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1347, in main
    app.TopWindow = SynthICCFrame()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 146, in __init__
    self.update_controls()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1219, in update_controls
    self.update_trc_controls()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1300, in update_trc_controls
    self.profile_class_ctrl.GetStringSelection() == self.profile_classes["scnr"]
KeyError: 'scnr'
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 549, in  │
│ main                                                                         │
│     _main(module, name, applockfilename)                                     │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 536, in  │
│ _main                                                                        │
│     main()                                                                   │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1347, in main                                                           │
│     app.TopWindow = SynthICCFrame()                                          │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 146, in __init__                                                        │
│     self.update_controls()                                                   │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1219, in update_controls                                                │
│     self.update_trc_controls()                                               │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1300, in update_trc_controls                                            │
│     self.profile_class_ctrl.GetStringSelection() ==                          │
│ self.profile_classes["scnr"]                                                 │
│ KeyError: 'scnr'                                                             │
└──────────────────────────────────────────────────────────────────────────────┘
Connection to 127.0.0.1:15411 failed: [Errno 111] Connection refused
Exiting displaycal-synthprofile
Ran application exit handlers

**Comment by eoyilmaz** [comment]
> Sille an issue:
> 
> ```shell
> displaycal-synthprofile
> Acquired lock file: <DisplayCAL.main.AppLock object at 0x7ff1bf47f2b0>
> displaycal-synthprofile 3.9.2 2022-04-30T16:13:37Z
> manjaro 21.2.6 Qonos x86_64
> Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
> Faulthandler 
> wxPython 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
> Encoding: utf-8
> File system encoding: utf-8
> Loading /home/christian/.config/DisplayCAL/DisplayCAL.ini
> Existing client using port 15411
> listening
> writing to lock file: port: 43455
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 549, in main
>     _main(module, name, applockfilename)
>   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 536, in _main
>     main()
>   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1347, in main
>     app.TopWindow = SynthICCFrame()
>   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 146, in __init__
>     self.update_controls()
>   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1219, in update_controls
>     self.update_trc_controls()
>   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1300, in update_trc_controls
>     self.profile_class_ctrl.GetStringSelection() == self.profile_classes["scnr"]
> KeyError: 'scnr'
> ┌──────────────────────────────────────────────────────────────────────────────┐
> │ Traceback (most recent call last):                                           │
> │   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 549, in  │
> │ main                                                                         │
> │     _main(module, name, applockfilename)                                     │
> │   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 536, in  │
> │ _main                                                                        │
> │     main()                                                                   │
> │   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
> │ line 1347, in main                                                           │
> │     app.TopWindow = SynthICCFrame()                                          │
> │   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
> │ line 146, in __init__                                                        │
> │     self.update_controls()                                                   │
> │   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
> │ line 1219, in update_controls                                                │
> │     self.update_trc_controls()                                               │
> │   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
> │ line 1300, in update_trc_controls                                            │
> │     self.profile_class_ctrl.GetStringSelection() ==                          │
> │ self.profile_classes["scnr"]                                                 │
> │ KeyError: 'scnr'                                                             │
> └──────────────────────────────────────────────────────────────────────────────┘
> Connection to 127.0.0.1:15411 failed: [Errno 111] Connection refused
> Exiting displaycal-synthprofile
> Ran application exit handlers
> ```

This is totally a different bug. Created a new ticket #97

**Comment by eoyilmaz** [comment]
@ctouz to other bug is fixed, please try it and report it on #97 if you still have an issue.

Btw, please use the ``develop`` branch to test the code.

**Comment by ctouz** [comment]
Works with develop branch.
