### ISSUE TITLE
[Feature Request] Option to re-take last measurement

### ISSUE THREAD

**Issue by mr-september** [eoyilmaz/displaycal-py3#92]
Sometimes, while measuring, some overlay occurs, possibly affecting the ongoing measurement.

For example, you have 2 monitors, and are working on Monitor 2 while calibrating Monitor 1. Things like Windows Defender prompts (dimming the whole screen) or the alternate-tab pop-up may draw over the calibration patch on Monitor 1.

Currently, you need to re-start the whole calibration (~30 mins to 1 hr for me).

Would be great if there's a button to press in such situations, to re-do the previous calibration patch (or multiple calibration patches) :)

**Comment by eoyilmaz** [comment]
I'm not sure if it is possible with ``dispread`` of Argyll.

**Comment by eoyilmaz** [comment]
I've checked the ``dispread`` command of ArgyllCMS, I was hopping that we can do something with the ``-C`` flag. But I don't think it is possible. So, the request should be made to ArgyllCMS first (https://www.argyllcms.com) and then we can implement it here in DisplayCAL.

So, I'm closing this request. Please re-open it, if something is changed on the ArgyllCMS side or you have a suggestion on how to do it technically.
