### ISSUE TITLE
pip install . fails          net.displaycal.DisplayCAL.appdata.xml      connected to #88?

### ISSUE THREAD

**Issue by reindeerphotode** [eoyilmaz/displaycal-py3#93]
Dear Erkan,

after:
`pip install -r requirements.txt
pip install .`

I got the error messages below.

The **dist** directory is not existing in my case.

Best regards

   Marc

P.S. direct installation, not in the virtual environment

error messages:

   installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      copying build/lib.linux-x86_64-cpython-38/DisplayCAL/__version__.py -> build/bdist.linux-x86_64/wheel/DisplayCAL
      running install_data
      error: can't copy '/home/marc/python/displaycal-py3/DisplayCAL/../dist/net.displaycal.DisplayCAL.appdata.xml': doesn't exist or not a regular file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for DisplayCAL
Failed to build DisplayCAL
ERROR: Could not build wheels for DisplayCAL, which is required to install pyproject.toml-based projects

**Comment by eoyilmaz** [comment]
Sorry for the inconvenience we are now updating the build system, the workaround is to run the following:

```shell
pip install -r requirements.txt
python setup.py install
pip install .
```

This is a little wonky, but it should solve your issue.

**Comment by reindeerphotode** [comment]
pip install .

gives:
Building wheels for collected packages: DisplayCAL
  Building wheel for DisplayCAL (pyproject.toml) ... done
  Created wheel for DisplayCAL: filename=DisplayCAL-3.9.0-cp38-cp38-linux_x86_64.whl size=8977874 sha256=4a58ae2748fca2304044f686736e87f2a9abc3a80cd88879dc99c08f761fbd08
  Stored in directory: /root/.cache/pip/wheels/52/a6/1b/d0a20f7d5c89939c08546bca3353dce33e249a1a7d81fa2185
Successfully built DisplayCAL
Installing collected packages: DisplayCAL
  Attempting uninstall: DisplayCAL
    Found existing installation: DisplayCAL 3.9.0
ERROR: Cannot uninstall 'DisplayCAL'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

(I try to uninstall the stuff)

**Comment by eoyilmaz** [comment]
Ah yeah sorry, because you have previously installed it you can do as follows:

``shell
pip install -r requirements.txt
python setup.py uninstall
python setup.py install
pip install .
```

**Comment by eoyilmaz** [comment]
That's good to know, if #83 is fixed it will be much easier to install it later on.

**Comment by reindeerphotode** [comment]
nope
I am to stupid...
even with a pre typed and then copied password.
for me it does not work...

**Comment by m4mbr3** [comment]
I ran in what it seems the same issue just now while trying to install displaycal. The installer is looking for net.displaycal.DisplayCAL.appdata.xml in the folder dist which does not exist while the actual filel is in the misc folder. By creating the dist folder and moving/copying the file there would allow you to complete the installation, however for a complete fix, setup.py should be updated.

**Comment by bhlevca** [comment]
I have the same problem. 
`dist` directory does not exist and `pip install .` assumes that the re are 2 files in that diorectory

-` copyright`
- `net.displaycal.DisplayCAL.appdata.xml `(it exists in the `misc` directory)

`copyright` does not exist at all 

I solved the issue by creating an empty copyright file and putting it in the `misc` and then I did a 

`ln -fs misc dist`

To fix the issue properly the copyright file needs to be created in the dist/misc file and then the `setup.py`  file needs to be fixed to  point to the appropriate directory.

Thanks for the port I really appreciate it!

**Comment by eoyilmaz** [comment]
Hey guys, sorry that I'm not able to look in to that these days, but I'm reading messages and I'll fix that as soon as possible.

**Comment by eoyilmaz** [comment]
Can you guys test it again, this should now be fixed. Oh the installation instructions has been updated too by the way:

From the README.md file:

```shell
git clone https://github.com/eoyilmaz/displaycal-py3
python -m venv ./displaycal_venv
source ./displaycal_venv/bin/activate  # Windows: .\displaycal_venv\Scripts\activate.bat
cd ./displaycal-py3/
pip install -r requirements.txt
python -m build
pip install dist/DisplayCAL-3.9.0-*.whl
```

**Comment by bhlevca** [comment]
Install works now! Thanks

**Comment by eoyilmaz** [comment]
That's cool!
Closing the issue then :+1:
